### PR TITLE
Added OLLAMA_DEFAULT_KEEPALIVE, OLLAMA_KEEPALIVE environment variables

### PR DESCRIPTION
**Pull request by Chris-AS1**
This pull request introduces the ability to set `keep_alive` via the environment variable `OLLAMA_KEEPALIVE`. It currently supports both `generate` and `chat` endpoints.
I added tests to verify the parsing, as it was inconsistent without a dedicated marshalling function.

This is related to #2146.

### CODE REVIEW

**Comment by rcgtnick** [comment]
This would be nice to have for my use case - running Ollama with a single model in production for many users.

**Comment by rnldtsai** [comment]
This would be a helpful feature. Thanks.

**Comment by uxfion** [comment]
Is this effective on `/v1/chat/completions` endpoint?
https://github.com/ollama/ollama/issues/2508#issue-2135638897
If this is useful, it means a lot to me.🥺

**Comment by Chris-AS1** [comment]
There seems to be a little confusion so I'd like to elaborate on how it works - given how this feature was originally implemented the `keep_alive` value is set by the client(s). This means this PR allows passing that value while using CLI commands such as `run`. 

I'm considering adding a new configuration variable `OLLAMA_DEFAULT_KEEPALIVE` that sets the default behavior on the server-side.
This way there will be two variables to control how long the model should stay loaded: one for clients and one on the server.

**Comment by ingo-m** [comment]
@Chris-AS1 thanks for the clarification.

For anyone else who got here while trying to figure out how to disable unloading of a deployed model (after 5 minutes), the following cron job (on the instance where the model is deployed with ollama) works perfectly fine for me:
```bash
*/4 * * * * curl http://localhost:11434/api/generate -d '{"model": "mixtral:8x7b-instruct-v0.1-q3_K_S"}'
```

As previously explained here: https://github.com/ollama/ollama/issues/2508#issuecomment-1947841101

**Comment by Chris-AS1** [comment]
I refactored `keep_alive` into a `SessionDuration` struct, this allows reading from customized environment variables such as `OLLAMA_DEFAULT_KEEPALIVE` and `OLLAMA_KEEPALIVE` to manually control server-side and client-side values respectively.
While a default value is always present server-side, it's made optional for clients. However when a client specifies a duration it will always override the server's configuration for that particular request.

Example:

| Server       | Client | Result |
| ------------ | ------ | ------ |
| 5m (default)   | nil    | 5m     |
| 5m (default)   | 10m    | 10m    |
| 30s          | 5m     | 5m     |

**Comment by rcgtnick** [comment]
I would have said the server value should override the client value.

If I'm running ollama locally with multiple models I can just not set the server param and then I can control model unloading via client params.

If I'm deploying a server for a whole team, I want to set the server param and not have one person's client param affect the other people on the team.

Not trying to take a hard stance, this is just my input. The feature will be nice to have either way, and thanks for the work!

**Comment by rnldtsai** [comment]
> I would have said the server value should override the client value.
> 
> If I'm running ollama locally with multiple models I can just not set the server param and then I can control model unloading via client params.
> 
> If I'm deploying a server for a whole team, I want to set the server param and not have one person's client param affect the other people on the team.
> 
> Not trying to take a hard stance, this is just my input. The feature will be nice to have either way, and thanks for the work!

This constitutes valuable feedback. It appears necessary to introduce two parameters from the server side: 1) a parameter to determine whether to allow the client to send a keep-alive value. If set to true, this would enable the client to override the corresponding server parameter; 2) a server parameter designated to establish the default keep-alive duration. This duration would serve as the default time frame for maintaining the model active in memory.

**Comment by rcgtnick** [comment]
That would also work nicely.

**Comment by wakawakaaa** [comment]
When will this be available? Its very useful feature. Thanks

**Comment by Chris-AS1** [comment]
@wakawakaaa Whenever maintainers will be able to take a look.

**Comment by pdevine** [comment]
Hey guys, I was out for a bit, missed this PR and simultaneously had written my own version. @Chris-AS1 thank you so much for submitting this! I pulled out the commit w/ the tests and carried it in the other PR. I did have to omit the struct test as it was having problems unmarshaling into an int vs a float64.

The change should be in the next version (0.1.29). Thank you again (and sorry about the slow response)!  I'll go ahead and close this commit.

**Comment by wakawakaaa** [comment]
Hello, In docker-compose.yml its not working. 

I have tried in docker-compose.yml. 


```yaml
    environment:
      OLLAMA_DEFAULT_KEEPALIVE: 30m
```

Please let me know, thanks

**Comment by Chris-AS1** [comment]
@wakawakaaa How's your client request looking like?

**Pull request closed without merging**
