### PR TITLE
Add Nosia to Community Integrations

### PR DESCRIPTION
**Pull request by cbldev**
### Summary

This PR updates the README file to include a new link to the [Nosia](https://github.com/nosia-ai/nosia) project in Ollama Community Integrations.

### Changes

- README.md: Added a new link to the Nosia project

### Integration

Nosia is a platform that allows you to run an AI model on your own data. It is designed to be easy to install and use.

### CODE REVIEW

**Review by jmorganca — APPROVED** [review]
Thanks for the PR!

**Comment by jmorganca** [comment]
Possible to rebase?

**Comment by jmorganca** [comment]
Sorry about that – one more rebase (and will make sure to get this merged)

**Comment by cbldev** [comment]
@jmorganca ready!

**Comment by cbldev** [comment]
@jmorganca prepared again

**Review by mchiang0610 — APPROVED** [review]

**Pull request merged**
