### PR TITLE
Add instructions for installing via Brew on Mac

### PR DESCRIPTION
**Pull request by imthath-m**

### CODE REVIEW

**Comment by startakovsky** [comment]
Is this a sanctioned method of installation? I thought the only legitimate method was to download the installer via the Ollama webpage.

**Comment by imthath-m** [comment]
I don't know who needs to "sanction" it. That is why I've created this PR.

AFAICT, Everything [here](https://github.com/Homebrew/homebrew-core/blob/master/Formula/o/ollama.rb) looks good and points to this ollama repo.

**Comment by startakovsky** [comment]
True @imthath-m, just being paranoid.

**Comment by jmorganca** [comment]
Hi there, would it be possible to add homebrew to the package manager list in https://github.com/ollama/ollama?tab=readme-ov-file#package-managers ?

So sorry for the delay in reviewing this PR and thanks so much for opening it. Given the amount of time it has been open, I'll close this, but feel free to create a new PR

**Pull request closed without merging**
