### PR TITLE
pulled model not found fix - added to FAQ

### PR DESCRIPTION
**Pull request by lambdaofgod**
I've added a fix by [sridvijay](https://github.com/sridvijay) from #3876 to the documentation.

### CODE REVIEW

**Comment by pdevine** [comment]
Hey @lambdaofgod . I'm actually a little confused by the PR. This would just result in the model being pulled over again. If the model shares blobs (such as the weights) it would go quickly, but otherwise wouldn't do anything unexpected.

**Comment by lambdaofgod** [comment]
Well without doing this, when I pulled the model from CLI,  API was giving an error saying it doesn't exist.

**Comment by pdevine** [comment]
@lambdaofgod From the API it won't auto-pull, but it should from the CLI. There shouldn't be a case where a pulled model doesn't show up though. Do you know how to repro that?

**Comment by lambdaofgod** [comment]
The problem was that the model wasn't possible to use, even though it showed in models list. Basically everything was mentioned in the issue.

**Comment by pdevine** [comment]
There shouldn't be a case where the model is listed but can't be run. The `list` command in the client will fetch the list of models that it can run from the server. If there is a model which isn't working, we should just fix that. I'm going to go ahead and close the PR, but thank you for submitting it.

**Pull request closed without merging**
