### PR TITLE
Do no overwrite systemd service file

### PR DESCRIPTION
**Pull request by ex3ndr**
Currently during upgrade systemd file is lost, this fix avoid overwriting a file

### CODE REVIEW

**Review by pdevine — COMMENTED** [review]
The problem with not updating the service file if it exists is that if we need to make a change to the service file it wouldn't be possible with this change. I'm guessing that you have modified the service file which is why if this gets clobbered it's pretty annoying to have to reconstruct it.

Would it make sense to just back up the exist service file if it's different and install the new one? That way at least the file with the changes exists.

**Comment by hammeiam** [comment]
There's actually a better solution - `systemd` allows users to override a service file without actually modifying the base file itself. By using `sudo sustemctl edit ollama.service` you can keep your overrides even when ollama updates the underlying service.
https://askubuntu.com/questions/659267/how-do-i-override-or-configure-systemd-services

**Comment by mxyng** [comment]
As @hammeiam mentioned, the canonical way of modifying systemd services is to use the drop-in directory with overrides. There are examples in the [FAQ](https://github.com/jmorganca/ollama/blob/main/docs/faq.md)

**Comment by technovangelist** [comment]
But is the better way to achieve the goal to use a config file? Then we get a way to set settings that work on Linux and windows and Mac and we don't need to override it.

**Comment by jmorganca** [comment]
Hi @ex3ndr, thanks for the PR and great to see you 😊 

As a few people mentioned in the comments, would it be possible to use `sudo systemctl edit ollama.service` or the drop-in directory with overrides? Thanks so much

**Pull request closed without merging**
