### PR TITLE
feat: support num_ctx for `/v1/chat/completions`

### PR DESCRIPTION
**Pull request by wszgrcy**
https://github.com/ollama/ollama/issues/4447#issuecomment-2264425558

### CODE REVIEW

**Comment by thinkverse** [comment]
This does not follow OpenAI's API spec, as @mxyng commented in that issue https://github.com/ollama/ollama/issues/4447#issuecomment-2112784702, set the context in a Modelfile, or use Ollama's API. OpenAI's API doesn't allow setting the context length, hence Ollama's compatibility layer doesn't either.

**Comment by wszgrcy** [comment]
> This does not follow OpenAI's API spec, as @mxyng commented in that issue [#4447 (comment)](https://github.com/ollama/ollama/issues/4447#issuecomment-2112784702), set the context in a Modelfile, or use Ollama's API. OpenAI's API doesn't allow setting the context length, hence Ollama's compatibility layer doesn't either.

I also understand that adding this would compromise the elegance of the code
The purpose of using OpenAI compatible interfaces is to facilitate calling, but modifying 'Modelfile' has become very troublesome because there are no commands to directly modify it, and creating a 'Modelfile' is required`
If we really want to do this, we need to read the 'Modelfile' of the original model and insert parameters to create a new model. The process is too complicated and difficult to maintain (because we also need to delete content that is no longer in use, which will create a lot of redundancy)
At present, 'ollama run xxx' and then execute '/set parameter num_ctx 9999' can only take effect in the current conversation. It would be even better if a persistent modification command could be added, similar to 'ollama set xxxx' parameter num_ctx 9999`
Or can other methods be used to simplify this problem

**Comment by thinkverse** [comment]
> It would be even better if a persistent modification command could be added


You can create a Modelfile and use `ollama create` to save your model, then use that. It's all written in the Modefile documentation. https://github.com/ollama/ollama/blob/main/docs/modelfile.md#basic-modelfile

```
# Modelfile

# Specify the model you want to use
FROM llama3.1

# Modify its context length
PARAMETER num_ctx 4096
```

Then create a new model with `ollama create`.

```bash
ollama create my_model
```

If the Modelfile isn't in the same directory as you run `ollama create`, then supply the path to it using the `-f` flag.

```bash
ollama create my_model -f <Modelfile path>
```

Now you've created your own model with a modified context length, that you can use like any other Ollama model.

```js
const completion = await openai.chat.completions.create({
  model: 'my_model'
  messages: [{
    role: 'user',
    content: 'Say this is a test'
  }]
})
```

**Comment by wszgrcy** [comment]
> > It would be even better if a persistent modification command could be added
> 
> You can create a Modelfile and use `ollama create` to save your model, then use that. It's all written in the Modefile documentation. https://github.com/ollama/ollama/blob/main/docs/modelfile.md#basic-modelfile
> 
> ```
> # Modelfile
> 
> # Specify the model you want to use
> FROM llama3.1
> 
> # Modify its context length
> PARAMETER num_ctx 4096
> ```
> 
> Then create a new model with `ollama create`.
> 
> ```shell
> ollama create my_model
> ```
> 
> If the Modelfile isn't in the same directory as you run `ollama create`, then supply the path to it using the `-f` flag.
> 
> ```shell
> ollama create my_model -f <Modelfile path>
> ```
> 
> Now you've created your own model with a modified context length, that you can use like any other Ollama model.
> 
> ```js
> const completion = await openai.chat.completions.create({
>   model: 'my_model'
>   messages: [{
>     role: 'user',
>     content: 'Say this is a test'
>   }]
> })
> ```

Thank you for your reply, but I am currently testing the performance under multiple models
So I hope to have a relatively simple repair method
At present, it seems that only one modification can be made one by one

**Pull request closed without merging**
