### PR TITLE
server: skip blob verification for already verified blobs

### PR DESCRIPTION
**Pull request by bmizerany**
WIP.

This should also include a way to force verification via a flag or env or other means. I'll let the bike shedding begin on the _best_ way to handle that. :)

### CODE REVIEW

**Comment by LaurentBonnaud** [comment]
Thanks for implementing this!

**Comment by bmizerany** [comment]
@LaurentBonnaud Happy to! Is it working as expected for you?

**Review by pdevine — APPROVED** [review]

**Comment by mxyng** [comment]
`--always-verify` as a flag or `OLLAMA_ALWAYS_VERIFY` as env var should be fine

**Comment by bmizerany** [comment]
> `--always-verify` as a flag or `OLLAMA_ALWAYS_VERIFY` as env var should be fine

Regarding the flag: That seems a little obnixious for those that would want an "always verify" to be on...  always, since they would have to keep setting it for all pulls.

Let's assume we rule out the flag, and stick with an env. Stepping back a little from this narrow context, and I see `OLLAMA_ALWAYS_VERIFY` set in, say my `.profile` after months of not looking in there, or see it in a shell script, its pretty ambiguous, especially considering proposals for skipping TLS verification in https://github.com/ollama/ollama/pull/4615.

Maybe `OLLAMA_BLOBS_PULL_VERIFY=<anything that looks boolean>`. I'm not in love with that, but not sure how best to differentiate.

**Comment by bmizerany** [comment]
In the spirit of shipping things up, I'm punting on a "always verify checksums" flag or env, which can alway come in a future PR should enough evidence show it is truly needed.

**Comment by LaurentBonnaud** [comment]
Thanks for the merge!

**Pull request merged**
