### PR TITLE
Add Braina AI as an Ollama Desktop GUI

### PR DESCRIPTION
**Pull request by wallacelance**
### Overview
[Braina](https://www.brainasoft.com/braina/) supports Ollama natively on Windows. It automatically synchronizes with Ollama model lists, and allows users to use advanced features such as Voice (Both Speech to Text and Text to Speech), Web Search, File and Webpage attachments, Custom Prompts etc.

### Screenshots
**Main Chat UI**

LLM_Movies_results_with_web_access_Ollama_UI

**Model Management**

manage-language-models

### CODE REVIEW

**Comment by strfic** [comment]
Useful. I prefer Braina over WebUI when I am using my Windows machine.

**Review by strfic — APPROVED** [review]
Useful. I prefer Braina over WebUI when I am using my Windows machine.

**Comment by jmorganca** [comment]
@wallacelance cool project! Possible to rebase this PR?

**Comment by wallacelance** [comment]
> @wallacelance cool project! Possible to rebase this PR?

Done

**Pull request closed without merging**
