### PR TITLE
Adding 'Ollama App' as community integrations

### PR DESCRIPTION
**Pull request by JHubi1**
A little while back, I created an app to interact with Ollama from your phone called 'Ollama App'. I know, very creative, but the name stuck. I'd be very happy if it could be added to the integrations list.

At the moment, I only recommend using the mobile version, it's the most stable one, and the only one with a stable build, but I am cooking around a few other platforms (Flutter really is fabulous with multiplatform), like Desktop and maybe Web. When I'd decide to remove the experimental tag, where should I put them? Should I copy the entry and put it into multiple categories?

Thank you

### CODE REVIEW

**Comment by JHubi1** [comment]
@jmorganca @BruceMacD I saw you approving some other community integrations. May I at least get a comment about my app? Thank you

**Comment by JHubi1** [comment]
So, @jmorganca @BruceMacD @technovangelist @BruceMacD @pdevine (idk who else to mention), it's been almost two months since I opened this pull request. I really don't want to seem pushy, but please give me at least some comment; other requests have being approved in just a few days. I really built my app because I love your software and hoped some may like it; and people do. The repo gained almost 500 people staring it.
Since this pull request has been opened, I've added desktop support, web support is on the way. That's the reason I added my project to the desktop section. And I saw many recently added projects using a description, so I added one as well.

**Review by vignesh1507 — COMMENTED** [review]
great work @JHubi1

**Review by BruceMacD — APPROVED** [review]
Sorry for the delay, this one slipped through the cracks. Thanks for the contribution, this project looks great!

**Pull request merged**
