### PR TITLE
feat: Support Moore Threads GPU

### PR DESCRIPTION
**Pull request by yeahdongcn**
[Moore Threads](https://en.mthreads.com/), a cutting-edge GPU startup, introduces MUSA (Moore Threads Unified System Architecture) as its foundational technology. This pull request marks the initial integration of MTGPU support into Ollama, leveraging MUSA's capabilities to enhance LLM inference performance.

I also sent a [PR](https://github.com/ggerganov/llama.cpp/pull/8383) to [llama.cpp](https://github.com/ggerganov/llama.cpp) to integrate MTGPU.

Tested models are:

```bash
NAME                    ID              SIZE    MODIFIED     
mistral:latest          2ae6f6dd7a3d    4.1 GB  22 hours ago
llama3:8b-instruct-fp16 c666fe422df7    16 GB   30 hours ago
qwen2:72b               14066dfa503f    41 GB   2 days ago  
nomic-embed-text:latest 0a109f422b47    274 MB  2 days ago  
llama3:latest           365c0bd3c000    4.7 GB  3 days ago  
tinyllama:latest        2644915ede35    637 MB  3 days ago  
```

Screenshot:

Screenshot 2024-10-29 at 09 30 46

### CODE REVIEW

**Comment by yeahdongcn** [comment]
In the latest commit, `MUSA` packaging is completely separate from `CUDA`:

```bash
root@ab4512977e42:/tmp/ollama1008564665# tree .
.
|-- ollama.pid
`-- runners
    |-- cpu
    |   `-- ollama_llama_server
    `-- musa_v1
        |-- libmublas.so
        |-- libmusa.so.1.0
        |-- libmusart.so.1.0
        `-- ollama_llama_server

3 directories, 6 files
```

**Comment by yeahdongcn** [comment]
Since [PR #8383](https://github.com/ggerganov/llama.cpp/pull/8383) has been merged in [llama.cpp](https://github.com/ggerganov/llama.cpp), @jmorganca could you please review this PR? Thanks!

**Comment by yeahdongcn** [comment]
Full logs for running `llama3.1`:

```logs
$ docker logs -f ollama
2024/08/29 00:46:45 routes.go:1125: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: MUSA_VISIBLE_DEVICES: OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_HOST:http://0.0.0.0:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_LLM_LIBRARY: OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:/root/.ollama/models OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://*] OLLAMA_RUNNERS_DIR: OLLAMA_SCHED_SPREAD:false OLLAMA_TMPDIR: ROCR_VISIBLE_DEVICES:]"
time=2024-08-29T00:46:45.035Z level=INFO source=images.go:753 msg="total blobs: 33"
time=2024-08-29T00:46:45.036Z level=INFO source=images.go:760 msg="total unused blobs removed: 0"
time=2024-08-29T00:46:45.037Z level=INFO source=routes.go:1172 msg="Listening on [::]:11434 (version 0.3.8-9-g95bc999-dirty)"
time=2024-08-29T00:46:45.037Z level=INFO source=payload.go:30 msg="extracting embedded files" dir=/tmp/ollama3381926676/runners
time=2024-08-29T00:46:56.127Z level=INFO source=payload.go:44 msg="Dynamic LLM libraries [musa_v1 cpu cpu_avx cpu_avx2 cuda_v11 cuda_v12]"
time=2024-08-29T00:46:56.127Z level=INFO source=gpu.go:202 msg="looking for compatible GPUs"
time=2024-08-29T00:46:56.127Z level=INFO source=gpu.go:679 msg="found gpu dependency libraries" path=/usr/lib/ollama
time=2024-08-29T00:46:56.127Z level=INFO source=gpu.go:679 msg="found gpu dependency libraries" path=/usr/lib/ollama
time=2024-08-29T00:46:56.128Z level=INFO source=gpu.go:679 msg="found gpu dependency libraries" path=/usr/lib/ollama
time=2024-08-29T00:46:56.129Z level=WARN source=musa_linux.go:35 msg="ollama recommends running the https://www.mthreads.com/pes/drivers/index" error="mtgpu driver version not implemented"
time=2024-08-29T00:46:56.130Z level=INFO source=types.go:114 msg="inference compute" id=0 library=musa variant="" compute="" driver=0.0 name=1ed5:0323 total="48.0 GiB" available="48.0 GiB"
[GIN] 2024/08/29 - 00:47:15 | 200 |    1.019298ms |      172.18.0.3 | GET      "/api/tags"
[GIN] 2024/08/29 - 00:49:12 | 200 |       42.42µs |       127.0.0.1 | HEAD     "/"
[GIN] 2024/08/29 - 00:49:13 | 200 |   19.443837ms |       127.0.0.1 | POST     "/api/show"
time=2024-08-29T00:49:13.073Z level=INFO source=sched.go:715 msg="new model will fit in available VRAM in single GPU, loading" model=/root/.ollama/models/blobs/sha256-87048bcd55216712ef14c11c2c303728463207b165bf18440b9b84b07ec00f87 gpu=0 parallel=4 available=51529523200 required="6.0 GiB"
time=2024-08-29T00:49:13.074Z level=INFO source=memory.go:309 msg="offload to musa" layers.requested=-1 layers.model=33 layers.offload=33 layers.split="" memory.available="[48.0 GiB]" memory.required.full="6.0 GiB" memory.required.partial="6.0 GiB" memory.required.kv="1.0 GiB" memory.required.allocations="[6.0 GiB]" memory.weights.total="4.7 GiB" memory.weights.repeating="4.3 GiB" memory.weights.nonrepeating="411.0 MiB" memory.graph.full="560.0 MiB" memory.graph.partial="677.5 MiB"
time=2024-08-29T00:49:13.080Z level=INFO source=server.go:391 msg="starting llama server" cmd="/tmp/ollama3381926676/runners/musa_v1/ollama_llama_server --model /root/.ollama/models/blobs/sha256-87048bcd55216712ef14c11c2c303728463207b165bf18440b9b84b07ec00f87 --ctx-size 8192 --batch-size 512 --embedding --log-disable --n-gpu-layers 33 --parallel 4 --port 43739"
time=2024-08-29T00:49:13.080Z level=INFO source=sched.go:450 msg="loaded runners" count=1
time=2024-08-29T00:49:13.080Z level=INFO source=server.go:592 msg="waiting for llama runner to start responding"
time=2024-08-29T00:49:13.081Z level=INFO source=server.go:626 msg="waiting for server to become available" status="llm server error"
INFO [main] build info | build=317 commit="1e6f6554a" tid="140675977272000" timestamp=1724892553
INFO [main] system info | n_threads=64 n_threads_batch=-1 system_info="AVX = 1 | AVX_VNNI = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | AVX512_BF16 = 0 | FMA = 0 | NEON = 0 | SVE = 0 | ARM_FMA = 0 | F16C = 0 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 1 | " tid="140675977272000" timestamp=1724892553 total_threads=128
INFO [main] HTTP server listening | hostname="127.0.0.1" n_threads_http="127" port="43739" tid="140675977272000" timestamp=1724892553
llama_model_loader: loaded meta data with 29 key-value pairs and 291 tensors from /root/.ollama/models/blobs/sha256-87048bcd55216712ef14c11c2c303728463207b165bf18440b9b84b07ec00f87 (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.type str              = model
llama_model_loader: - kv   2:                               general.name str              = Meta Llama 3.1 8B Instruct
llama_model_loader: - kv   3:                           general.finetune str              = Instruct
llama_model_loader: - kv   4:                           general.basename str              = Meta-Llama-3.1
llama_model_loader: - kv   5:                         general.size_label str              = 8B
llama_model_loader: - kv   6:                            general.license str              = llama3.1
llama_model_loader: - kv   7:                               general.tags arr[str,6]       = ["facebook", "meta", "pytorch", "llam...
llama_model_loader: - kv   8:                          general.languages arr[str,8]       = ["en", "de", "fr", "it", "pt", "hi", ...
llama_model_loader: - kv   9:                          llama.block_count u32              = 32
llama_model_loader: - kv  10:                       llama.context_length u32              = 131072
llama_model_loader: - kv  11:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv  12:                  llama.feed_forward_length u32              = 14336
llama_model_loader: - kv  13:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv  14:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv  15:                       llama.rope.freq_base f32              = 500000.000000
llama_model_loader: - kv  16:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  17:                          general.file_type u32              = 2
llama_model_loader: - kv  18:                           llama.vocab_size u32              = 128256
llama_model_loader: - kv  19:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv  20:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  21:                         tokenizer.ggml.pre str              = llama-bpe
llama_model_loader: - kv  22:                      tokenizer.ggml.tokens arr[str,128256]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  23:                  tokenizer.ggml.token_type arr[i32,128256]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  24:                      tokenizer.ggml.merges arr[str,280147]  = ["Ġ Ġ", "Ġ ĠĠĠ", "ĠĠ ĠĠ", "...
llama_model_loader: - kv  25:                tokenizer.ggml.bos_token_id u32              = 128000
llama_model_loader: - kv  26:                tokenizer.ggml.eos_token_id u32              = 128009
llama_model_loader: - kv  27:                    tokenizer.chat_template str              = {% set loop_messages = messages %}{% ...
llama_model_loader: - kv  28:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type q4_0:  225 tensors
llama_model_loader: - type q6_K:    1 tensors
time=2024-08-29T00:49:13.331Z level=INFO source=server.go:626 msg="waiting for server to become available" status="llm server loading model"
llm_load_vocab: special tokens cache size = 256
llm_load_vocab: token to piece cache size = 0.7999 MB
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = BPE
llm_load_print_meta: n_vocab          = 128256
llm_load_print_meta: n_merges         = 280147
llm_load_print_meta: vocab_only       = 0
llm_load_print_meta: n_ctx_train      = 131072
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_swa            = 0
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 4
llm_load_print_meta: n_embd_k_gqa     = 1024
llm_load_print_meta: n_embd_v_gqa     = 1024
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale    = 0.0e+00
llm_load_print_meta: n_ff             = 14336
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 500000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_ctx_orig_yarn  = 131072
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: model type       = 8B
llm_load_print_meta: model ftype      = Q4_0
llm_load_print_meta: model params     = 8.03 B
llm_load_print_meta: model size       = 4.33 GiB (4.64 BPW)
llm_load_print_meta: general.name     = Meta Llama 3.1 8B Instruct
llm_load_print_meta: BOS token        = 128000 '<|begin_of_text|>'
llm_load_print_meta: EOS token        = 128009 '<|eot_id|>'
llm_load_print_meta: LF token         = 128 'Ä'
llm_load_print_meta: EOT token        = 128009 '<|eot_id|>'
llm_load_print_meta: max token length = 256
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 MUSA devices:
  Device 0: MTT S4000, compute capability 2.2, VMM: no
llm_load_tensors: ggml ctx size =    0.27 MiB
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 33/33 layers to GPU
llm_load_tensors:      MUSA0 buffer size =  4155.99 MiB
llm_load_tensors:        CPU buffer size =   281.81 MiB
llama_new_context_with_model: n_ctx      = 8192
llama_new_context_with_model: n_batch    = 512
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: flash_attn = 0
llama_new_context_with_model: freq_base  = 500000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:      MUSA0 KV buffer size =  1024.00 MiB
llama_new_context_with_model: KV self size  = 1024.00 MiB, K (f16):  512.00 MiB, V (f16):  512.00 MiB
llama_new_context_with_model:  MUSA_Host  output buffer size =     2.02 MiB
llama_new_context_with_model:      MUSA0 compute buffer size =   560.00 MiB
llama_new_context_with_model:  MUSA_Host compute buffer size =    24.01 MiB
llama_new_context_with_model: graph nodes  = 1030
llama_new_context_with_model: graph splits = 2
INFO [main] model loaded | tid="140675977272000" timestamp=1724892555
time=2024-08-29T00:49:15.838Z level=INFO source=server.go:631 msg="llama runner started in 2.76 seconds"
[GIN] 2024/08/29 - 00:49:15 | 200 |  2.823850523s |       127.0.0.1 | POST     "/api/chat"
```

**Comment by yeahdongcn** [comment]
Since MUSA doesn't currently support Windows, I added an empty implementation for MUSA on Windows to ensure all checks pass.

**Comment by richardnnn** [comment]
As a personal Moore Threads GPU owner, I Would appreciate if this can get merged or at least receive more attention from the code approvers

**Comment by gliangMT** [comment]
As an MTT S80 user, I would appreciate if this PR can get merged @jmorganca

**Pull request closed without merging**
