### PR TITLE
Add Community Integration: Chatbox

### PR DESCRIPTION
**Pull request by Bin-Huang**
Thank you so much for developing Ollama; it has made running llama2 on my Mac incredibly simple. I've completely forgotten how I used to handle all the dependencies myself.

Recently, I've added support for Ollama's locally deployed models to my project [Chatbox](https://github.com/Bin-Huang/chatbox) (in the [latest release](https://github.com/Bin-Huang/chatbox/releases)), and now Chatbox + Ollama is just fantastic.🍻

Dec-25-2023 17-38-17

### CODE REVIEW

**Review by technovangelist — APPROVED** [review]
hi @Bin-Huang this looks like a great addition to the community integrations section on the Ollama readme. Thanks so much for submitting it and for being part of this community

**Comment by jmorganca** [comment]
Thanks so much for the PR. Possible to rebase?

Also:
- Would it be okay to add to the bottom of the list for now (I will re-sort them at a later point)
- It seems like this is more of a desktop app – would it be possible to only add it to that category (just so we don't have doubleS)

**Comment by Bin-Huang** [comment]
Of course, I have no questions about the order. By the way, I have also developed the mobile version of Chatbox (not open source). If we only list the open-source ones, we can remove it.

**Comment by jmorganca** [comment]
Thanks so much! No worries. I think for now just add it to the Web section and remove the mobile section entry. And don't forget to rebase!

**Pull request merged**
