### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Drlordbasil**
add my embedding example for ollama, but it includes Groq API calls too, is this allowed?

### CODE REVIEW

**Comment by jmorganca** [comment]
@Drlordbasil would it be possible to rebase? Thanks!

**Comment by Drlordbasil** [comment]
Not sure honestly. 😕 I can definitely make a simple one easily though but
basic tool calls with groq or local models, but I thought yall had a due
date

**Comment by Drlordbasil** [comment]
I am making a tools website with it integrated.  Unfortunately im a broke
ass that spends my money on research for more. I'll get paid next week and
launch the live demo. For now I'll keep polishing it as a normal financial
advisor and then add requirements needed. Current one now accepts base
parameters like cost of living and bills alongside income and savings
parameters. 😒 I want it better muahah as I have adhd (untreated) and suck
with finances too.

**Comment by mchiang0610** [comment]
Hey, thank you so much for the contribution. I really appreciate it. 

I'm trying to keep this as integrations instead of examples just to keep it simple.

**Pull request closed without merging**
