### PR TITLE
Added grammar (and json schemas and CPU-only Dockerfile) support (from ollama/ollama PR #1606)

### PR DESCRIPTION
**Pull request by markcda**
Updated version of #1606.

### CODE REVIEW

**Comment by qkxie** [comment]
waiting for merging

**Comment by mitar** [comment]
This looks really cool. Could this be merged? It is a simple PR which just passes options to llama.cpp.

**Comment by mitar** [comment]
Also, it would be useful to have llama.cpp which includes https://github.com/ggerganov/llama.cpp/pull/6811 and https://github.com/ggerganov/llama.cpp/pull/7424 because they bring performance improvements to grammar sampling.

**Comment by markcda** [comment]
> Also, it would be useful to have llama.cpp which includes [ggerganov/llama.cpp#6811](https://github.com/ggerganov/llama.cpp/pull/6811) and [ggerganov/llama.cpp#7424](https://github.com/ggerganov/llama.cpp/pull/7424) because they bring performance improvements to grammar sampling.

I think I can merge it to my fork for now while this pull request wasn't merged.

**Comment by mitar** [comment]
@markcda This PR is pretty ugly because you made PR from the main branch of your fork, not a feature branch. Also, you are merging upstream (this repository) changes into your branch, instead of rebasing. So there is bunch of useless commits from the view of this repository.

**Comment by mitar** [comment]
Also why is CPU only Dockerfile part of this PR and not some other PR?

**Comment by coder543** [comment]
@mitar are you one of the maintainers here? These things would only matter if the maintainers were reviewing this PR... so far, they've shown no inclination to accept any of the grammar PRs.

**Comment by mitar** [comment]
No, I am not. But if PR hopes to be merged at all, then this matters. In general it is a good etiquette. Otherwise what's the point of the MR?

**Comment by coder543** [comment]
We don’t know what the maintainers care about.

**Comment by mitar** [comment]
I do not think this works for JSON Schema. The ext_server does not support JSON schema field.

**Comment by Kinglord** [comment]
Hey all, I know there's an automated ping here but just to better align everyone please check out and comment on my new call to the Ollama team for clarity here. As always please be civil and stay on topic! 😄 - https://github.com/ollama/ollama/issues/6237

**Pull request closed without merging**
