### PR TITLE
suppress ollama_llama_server.exe blank command window popup

### PR DESCRIPTION
**Pull request by ashokgelal**

### CODE REVIEW

**Comment by jmorganca** [comment]
I can't seem to reproduce this – how did you trigger it (do you have a screenshot etc?)

**Comment by jmorganca** [comment]
Also: thanks for the PR!

**Comment by ashokgelal** [comment]
It's kind of hard to repro but it's definitely reproducible. I'm working on an app that in a way embeds Ollama (downloads Ollama and runs `serve` in the "background" by spawning a process). The blank window pops up every time you interact with any model. More annoyingly, even if you minimize it, it randomly brings it to the foreground. 

> Also: thanks for the PR!

Actually, thank you for Ollama. Took me a couple of days to actually nail this down but I had fun learning the code base and hopefully will be able to contribute more in the future.


PS: I built Ollama locally and used the new exe and verified that this PR fixes it. Also, it doesn't seem to impact any of the current behavior.

image

**Comment by ashokgelal** [comment]
@jmorganca any thoughts about this? Please Let me know if you need anything else from my side.

**Comment by ashokgelal** [comment]
After some further testing, I found out that just the `cmd.SysProcAttr = &syscall.SysProcAttr{CreationFlags: 0x08000000}`, solves this issue and don't need to use cmd_path (I was trying to mimic https://github.com/ollama/ollama/blob/4ec7445a6f678b6efc773bb9fa886d7c9b075577/cmd/start_windows.go#L40). 

@jmorganca Should I create another PR and close this or just update this PR?

**Comment by BrunoGeorgevich** [comment]
I have the same issue!

**Comment by ashokgelal** [comment]
@jmorganca I just tested it with Ollama 0.5.1 and it still is an issue. 
image

**Comment by clduab11** [comment]
New user, also an issue with 0.5.3!

**Comment by ashokgelal** [comment]
@jmorganca I've sent a new PR here, can you please look at it? https://github.com/ollama/ollama/pull/8668

**Pull request closed without merging**
