### PR TITLE
Add 'Knowledge Cutoff' column to model library table

### LINKED ISSUE #3412: Add knowledge cutoffs for different available models
### What are you trying to do?

_No response_

### How should we solve this?

_No response_

### What is the impact of not solving this?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by saket3199**
resolves #3412

### CODE REVIEW

**Comment by jmorganca** [comment]
Hi there! Thanks for the PR. As much as it's good to know this, the table might start get too wide in the README.md. Would it be possible to host this in a different repo or Gist etc?

**Comment by saketSwabhav** [comment]
Hi! Thank you for your feedback. I understand your concern about the width of the table in the README.md file. In the next PR, I will move the table to a Gist and link it in the README.md file. This should help maintain the readability of the README.md file while still providing the necessary information. Thanks again for your suggestion!

**Review by hamirmahal — COMMENTED** [review]
The table looks okay on a 16:10 monitor.

image

**Comment by hamirmahal** [comment]
I think having everything in one place will make the cutoffs dates easier to maintain and verify.

**Comment by hamirmahal** [comment]
@jmorganca If the cutoff dates are in a separate repository or gist, it's easier for them to be outdated or incorrect, especially if that repository or gist isn't owned by `ollama`.

If the cutoff dates aren't in `README.md` directly, maybe they can go in a `KnowledgeCutoffs.md` file linked from `README.md`?

**Comment by saketSwabhav** [comment]
> @jmorganca If the cutoff dates are in a separate repository or gist, it's easier for them to be outdated or incorrect, especially if that repository or gist isn't owned by `ollama`.
> 
> If the cutoff dates aren't in `README.md` directly, maybe they can go in a `KnowledgeCutoffs.md` file linked from `README.md`?

yes, I do believe the same we can link it here as well or the gist, whereas I have created a separate gist as well #3428

**Pull request closed without merging**
