### PR TITLE
openai: support for structured outputs

### PR DESCRIPTION
**Pull request by iscy**
This PR is enabling the [Structured Outputs](https://platform.openai.com/docs/guides/structured-outputs/supported-schemas) feature available on OpenAI.

Using the math reasoning example they have on their website, here's the response of both OpenAI and Ollama using the exact same request:

OpenAI (gpt-4o-2024-08-06)
```
{
  "steps": [
    {
      "explanation": "We start with the equation 8x + 7 = -23. Our goal is to isolate x on one side of the equation.",
      "output": "8x + 7 = -23"
    },
    {
      "explanation": "Subtract 7 from both sides to begin isolating the term with x. This will help us get rid of the constant term on the left side.",
      "output": "8x + 7 - 7 = -23 - 7"
    },
    {
      "explanation": "Simplify both sides of the equation. On the left side, 7 - 7 cancels out, leaving us with 8x. On the right side, -23 - 7 equals -30.",
      "output": "8x = -30"
    },
    {
      "explanation": "Now, divide both sides by 8 to solve for x. This will isolate x completely.",
      "output": "8x / 8 = -30 / 8"
    },
    {
      "explanation": "Simplify the right side of the equation. -30 divided by 8 simplifies to -3.75.",
      "output": "x = -3.75"
    }
  ],
  "final_answer": "x = -3.75"
}
```

Ollama (llama3.1:8b)
```
{
  "steps": [
    {
      "explanation": "The first step is to isolate the term with the variable (in this case, x) on one side of the equation.",
      "output": "Subtract 7 from both sides: 8x + 7 - 7 = -23 - 7"
    },
    {
      "explanation": "This simplifies to:",
      "output": "8x = -30"
    },
    {
      "explanation": "The next step is to get rid of the coefficient (the number being multiplied by x).",
      "output": "Divide both sides by 8: 8x / 8 = -30 / 8"
    },
    {
      "explanation": "This simplifies to:",
      "output": "x = -3.75"
    }
  ],
  "final_answer": "-3.75"
}
```

### CODE REVIEW

**Review by vioricavg — APPROVED** [review]

**Comment by Getty** [comment]
I just want to add up that this works marvelous, please merge quick :D

**Comment by boldviking** [comment]
I can confirm that this is working as intended :).

I had some trouble as I was using the wrong endpoint. Be sure to use /v1/chat/completion and not just /api/chat like I did, else you will run into trouble xD.

Would love to see this in the main branch soon

**Comment by dhiltgen** [comment]
Thanks for taking the time to post a PR. I noticed you've made some changes to server.cpp, so I wanted to let you know that we're about to merge another PR (#5034) to begin replacing that code with a new Go based equivalent. The goal of this is to add more unit testing and fix some long standing stability bugs while preserving vision model support. If you need help rebasing your PR don't hesitate to contact us by replying here.

**Comment by iscy** [comment]
> Thanks for taking the time to post a PR. I noticed you've made some changes to server.cpp, so I wanted to let you know that we're about to merge another PR (#5034) to begin replacing that code with a new Go based equivalent. The goal of this is to add more unit testing and fix some long standing stability bugs while preserving vision model support. If you need help rebasing your PR don't hesitate to contact us by replying here.

Hi Daniel, thank you for the heads up. You seem to be the first glancing over this PR as a maintainer, so here's my main question for the team: is there any interest in merging a PR to feature Structured Outputs in Ollama?

I'm asking this because there has been several attemps to work this out but none of them ever had a maintainer comment on it. I've seen my other PR merged, however this one never got any follow up. I don't mind re-working it out once #5034 is in, just wondering if it's worth it.

Thank you,

**Comment by iscy** [comment]
Closing this PR since the work to make it compatible with v0.4.x has been done in PR #7588 .

**Pull request closed without merging**
