### PR TITLE
added tools when `stream=true`

### LINKED ISSUE #5796: Streaming for tool calls is unsupported
### What is the issue?

Hi everyone!

I am trying to use tools in requests to `llama3-groq-tool-use:70b`. Here is simple code in Python using langchain==0.2.9:

```
from langchain_core.tools import tool
from langchain_openai import ChatOpenAI
from langchain.prompts import (
    ChatPromptTemplate,
    MessagesPlaceholder,
)
from langchain.agents import AgentExecutor, create_openai_tools_agent

@tool
def function_1(a: int, b: int) -> int:
    """uses function function_1 for arguments a and b."""
    return a % b + 2

@tool
def function_2(a: int, b: int) -> int:
    """uses function function_2 for arguments a and b."""
    return a * b + 1

tools = [function_1, function_2]


llm = ChatOpenAI(
    model="llama3-groq-tool-use:70b",
    temperature=0,
)

default_prompt = ChatPromptTemplate.from_messages(
        [
            ("system", "You are a helpful AI assistant."),
            MessagesPlaceholder("chat_history", optional=True),
            ("human", "{input}"),
            MessagesPlaceholder("agent_scratchpad"),
        ]
    )

input_message = "What is function_1(10, 11)? Also what is function_2(10, 11)?"

agent = create_openai_tools_agent(
    llm=llm,
    tools=tools,
    prompt=default_prompt
)

agent_executor = AgentExecutor(
    agent=agent,
    tools=tools,
    verbose=True,
    return_intermediate_steps=False,
)

res = agent_executor.invoke({"input": input_message})

print(res)
```

The result is following:
```
> Entering new AgentExecutor chain...
<tool_call>
{"id": 0, "name": "function_1", "arguments": {"a": 10, "b": 11}}
</tool_call>
<tool_call>
{"id": 1, "name": "function_2", "arguments": {"a": 10, "b": 11}}
</tool_call>

> Finished chain.
{
    'input': 'What is function_1(10, 11)? Also what is function_2(10, 11)?',
    'output': '<tool_call>\n{"id": 0, "name": "function_1", "arguments": {"a": 10, "b": 11}}\n</tool_call>\n<tool_call>\n{"id": 1, "name": "function_2", "arguments": {"a": 10, "b": 11}}\n</tool_call>'
}
```

If I am using `langchain_community.chat_models.ollama.ChatOllama` it output the same.

But if I use same model (`llama3-groq-70b-8192-tool-use-preview`) with groq OpenAI Compatible API, it uses tools and invokes the functions, output below:
```
> Entering new AgentExecutor chain...

Invoking: `function_1` with `{'a': 10, 'b': 11}`


12
Invoking: `function_2` with `{'a': 10, 'b': 11}`


111The result of function_1(10, 11) is 12, and the result of function_2(10, 11) is 111.

> Finished chain.
{
    'input': 'What is function_1(10, 11)? Also what is function_2(10, 11)?',
    'output': 'The result of function_1(10, 11) is 12, and the result of function_2(10, 11) is 111.'
}
```

Is it expected behaviour or this problem is it still in progress?
Many thanks

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.2.7

### PR DESCRIPTION
**Pull request by vertrue**
fixes #5796

```
curl --location '127.0.0.1:11434/v1/chat/completions' \
--header 'Content-Type: application/json' \
--data '{
  "messages": [
    {
      "content": "You are a helpful AI assistant that can use tools.",
      "role": "system"
    },
    {
      "content": "What is function_1(10, 11)? use provided tools",
      "role": "user"
    }
  ],
  "model": "llama3-groq-tool-use:8b",
  "logprobs": false,
  "n": 1,
  "stream": true,
  "temperature": 0,
  "tools": [
    {
      "type": "function",
      "function": {
        "name": "function_1",
        "description": "uses function function_1 for arguments a and b.",
        "parameters": {
          "type": "object",
          "properties": {
            "a": {
              "type": "integer"
            },
            "b": {
              "type": "integer"
            }
          },
          "required": [
            "a",
            "b"
          ]
        }
      }
    }
  ]
}'
```

chunks:
```
data: {"id":"chatcmpl-20","object":"chat.completion.chunk","created":1721830176,"model":"llama3-groq-tool-use:8b","system_fingerprint":"fp_ollama","choices":[{"index":0,"delta":{"role":"assistant","content":"\u003ctool_call\u003e"},"finish_reason":null}]}

data: {"id":"chatcmpl-20","object":"chat.completion.chunk","created":1721830176,"model":"llama3-groq-tool-use:8b","system_fingerprint":"fp_ollama","choices":[{"index":0,"delta":{"role":"assistant","content":"\n"},"finish_reason":null}]}

data: {"id":"chatcmpl-20","object":"chat.completion.chunk","created":1721830176,"model":"llama3-groq-tool-use:8b","system_fingerprint":"fp_ollama","choices":[{"index":0,"delta":{"role":"assistant","content":"{\""},"finish_reason":null}]}

data: {"id":"chatcmpl-20","object":"chat.completion.chunk","created":1721830176,"model":"llama3-groq-tool-use:8b","system_fingerprint":"fp_ollama","choices":[{"index":0,"delta":{"role":"assistant","content":"id"},"finish_reason":null}]}

data: {"id":"chatcmpl-20","object":"chat.completion.chunk","created":1721830176,"model":"llama3-groq-tool-use:8b","system_fingerprint":"fp_ollama","choices":[{"index":0,"delta":{"role":"assistant","content":"\":"},"finish_reason":null}]}

data: {"id":"chatcmpl-20","object":"chat.completion.chunk","created":1721830176,"model":"llama3-groq-tool-use:8b","system_fingerprint":"fp_ollama","choices":[{"index":0,"delta":{"role":"assistant","content":" "},"finish_reason":null}]}

data: {"id":"chatcmpl-20","object":"chat.completion.chunk","created":1721830176,"model":"llama3-groq-tool-use:8b","system_fingerprint":"fp_ollama","choices":[{"index":0,"delta":{"role":"assistant","content":"0"},"finish_reason":null}]}

data: {"id":"chatcmpl-20","object":"chat.completion.chunk","created":1721830176,"model":"llama3-groq-tool-use:8b","system_fingerprint":"fp_ollama","choices":[{"index":0,"delta":{"role":"assistant","content":","},"finish_reason":null}]}

data: {"id":"chatcmpl-20","object":"chat.completion.chunk","created":1721830176,"model":"llama3-groq-tool-use:8b","system_fingerprint":"fp_ollama","choices":[{"index":0,"delta":{"role":"assistant","content":" \""},"finish_reason":null}]}

data: {"id":"chatcmpl-20","object":"chat.completion.chunk","created":1721830176,"model":"llama3-groq-tool-use:8b","system_fingerprint":"fp_ollama","choices":[{"index":0,"delta":{"role":"assistant","content":"name"},"finish_reason":null}]}

data: {"id":"chatcmpl-20","object":"chat.completion.chunk","created":1721830176,"model":"llama3-groq-tool-use:8b","system_fingerprint":"fp_ollama","choices":[{"index":0,"delta":{"role":"assistant","content":"\":"},"finish_reason":null}]}

data: {"id":"chatcmpl-20","object":"chat.completion.chunk","created":1721830176,"model":"llama3-groq-tool-use:8b","system_fingerprint":"fp_ollama","choices":[{"index":0,"delta":{"role":"assistant","content":" \""},"finish_reason":null}]}

data: {"id":"chatcmpl-20","object":"chat.completion.chunk","created":1721830176,"model":"llama3-groq-tool-use:8b","system_fingerprint":"fp_ollama","choices":[{"index":0,"delta":{"role":"assistant","content":"function"},"finish_reason":null}]}

data: {"id":"chatcmpl-20","object":"chat.completion.chunk","created":1721830176,"model":"llama3-groq-tool-use:8b","system_fingerprint":"fp_ollama","choices":[{"index":0,"delta":{"role":"assistant","content":"_"},"finish_reason":null}]}

data: {"id":"chatcmpl-20","object":"chat.completion.chunk","created":1721830176,"model":"llama3-groq-tool-use:8b","system_fingerprint":"fp_ollama","choices":[{"index":0,"delta":{"role":"assistant","content":"1"},"finish_reason":null}]}

data: {"id":"chatcmpl-20","object":"chat.completion.chunk","created":1721830176,"model":"llama3-groq-tool-use:8b","system_fingerprint":"fp_ollama","choices":[{"index":0,"delta":{"role":"assistant","content":"\","},"finish_reason":null}]}

data: {"id":"chatcmpl-20","object":"chat.completion.chunk","created":1721830176,"model":"llama3-groq-tool-use:8b","system_fingerprint":"fp_ollama","choices":[{"index":0,"delta":{"role":"assistant","content":" \""},"finish_reason":null}]}

data: {"id":"chatcmpl-20","object":"chat.completion.chunk","created":1721830176,"model":"llama3-groq-tool-use:8b","system_fingerprint":"fp_ollama","choices":[{"index":0,"delta":{"role":"assistant","content":"arguments"},"finish_reason":null}]}

data: {"id":"chatcmpl-20","object":"chat.completion.chunk","created":1721830176,"model":"llama3-groq-tool-use:8b","system_fingerprint":"fp_ollama","choices":[{"index":0,"delta":{"role":"assistant","content":"\":"},"finish_reason":null}]}

data: {"id":"chatcmpl-20","object":"chat.completion.chunk","created":1721830176,"model":"llama3-groq-tool-use:8b","system_fingerprint":"fp_ollama","choices":[{"index":0,"delta":{"role":"assistant","content":" {\""},"finish_reason":null}]}

data: {"id":"chatcmpl-20","object":"chat.completion.chunk","created":1721830176,"model":"llama3-groq-tool-use:8b","system_fingerprint":"fp_ollama","choices":[{"index":0,"delta":{"role":"assistant","content":"a"},"finish_reason":null}]}

data: {"id":"chatcmpl-20","object":"chat.completion.chunk","created":1721830176,"model":"llama3-groq-tool-use:8b","system_fingerprint":"fp_ollama","choices":[{"index":0,"delta":{"role":"assistant","content":"\":"},"finish_reason":null}]}

data: {"id":"chatcmpl-20","object":"chat.completion.chunk","created":1721830177,"model":"llama3-groq-tool-use:8b","system_fingerprint":"fp_ollama","choices":[{"index":0,"delta":{"role":"assistant","content":" "},"finish_reason":null}]}

data: {"id":"chatcmpl-20","object":"chat.completion.chunk","created":1721830177,"model":"llama3-groq-tool-use:8b","system_fingerprint":"fp_ollama","choices":[{"index":0,"delta":{"role":"assistant","content":"10"},"finish_reason":null}]}

data: {"id":"chatcmpl-20","object":"chat.completion.chunk","created":1721830177,"model":"llama3-groq-tool-use:8b","system_fingerprint":"fp_ollama","choices":[{"index":0,"delta":{"role":"assistant","content":","},"finish_reason":null}]}

data: {"id":"chatcmpl-20","object":"chat.completion.chunk","created":1721830177,"model":"llama3-groq-tool-use:8b","system_fingerprint":"fp_ollama","choices":[{"index":0,"delta":{"role":"assistant","content":" \""},"finish_reason":null}]}

data: {"id":"chatcmpl-20","object":"chat.completion.chunk","created":1721830177,"model":"llama3-groq-tool-use:8b","system_fingerprint":"fp_ollama","choices":[{"index":0,"delta":{"role":"assistant","content":"b"},"finish_reason":null}]}

data: {"id":"chatcmpl-20","object":"chat.completion.chunk","created":1721830177,"model":"llama3-groq-tool-use:8b","system_fingerprint":"fp_ollama","choices":[{"index":0,"delta":{"role":"assistant","content":"\":"},"finish_reason":null}]}

data: {"id":"chatcmpl-20","object":"chat.completion.chunk","created":1721830177,"model":"llama3-groq-tool-use:8b","system_fingerprint":"fp_ollama","choices":[{"index":0,"delta":{"role":"assistant","content":" "},"finish_reason":null}]}

data: {"id":"chatcmpl-20","object":"chat.completion.chunk","created":1721830177,"model":"llama3-groq-tool-use:8b","system_fingerprint":"fp_ollama","choices":[{"index":0,"delta":{"role":"assistant","content":"11"},"finish_reason":null}]}

data: {"id":"chatcmpl-20","object":"chat.completion.chunk","created":1721830177,"model":"llama3-groq-tool-use:8b","system_fingerprint":"fp_ollama","choices":[{"index":0,"delta":{"role":"assistant","content":"}}\n"},"finish_reason":null}]}

data: {"id":"chatcmpl-20","object":"chat.completion.chunk","created":1721830177,"model":"llama3-groq-tool-use:8b","system_fingerprint":"fp_ollama","choices":[{"index":0,"delta":{"role":"assistant","content":"\u003c/tool_call\u003e"},"finish_reason":null}]}

data: {"id":"chatcmpl-20","object":"chat.completion.chunk","created":1721830177,"model":"llama3-groq-tool-use:8b","system_fingerprint":"fp_ollama","choices":[{"index":0,"delta":{"role":"assistant","content":"","tool_calls":[{"id":"call_ejieksiz","type":"function","function":{"name":"function_1","arguments":"{\"a\":10,\"b\":11}"}}]},"finish_reason":"tool_calls"}]}

data: [DONE]
```

last chunk:
```
{
  "id": "chatcmpl-20",
  "object": "chat.completion.chunk",
  "created": 1721830177,
  "model": "llama3-groq-tool-use:8b",
  "system_fingerprint": "fp_ollama",
  "choices": [
    {
      "index": 0,
      "delta": {
        "role": "assistant",
        "content": "",
        "tool_calls": [
          {
            "id": "call_ejieksiz",
            "type": "function",
            "function": {
              "name": "function_1",
              "arguments": "{\"a\":10,\"b\":11}"
            }
          }
        ]
      },
      "finish_reason": "tool_calls"
    }
  ]
}
```

also works with `/api/chat`
also added `"finish_reason": "tool_calls"` for completions

### CODE REVIEW

**Comment by wimmol** [comment]
its exactly Im looking for. ty a lot

**Comment by vertrue** [comment]
@royjhan I believe your PR is not fixing problem with the stream. Should I leave this PR open?

**Comment by royjhan** [comment]
> @royjhan I believe your merged PR is not fixing problem with the stream. Should I leave this PR opened?

Yes, the pr is not for streaming. Adding support stream=true requires deeper changes in ollama that differentiates tool calls from content, on the radar

**Comment by vertrue** [comment]
> > @royjhan I believe your merged PR is not fixing problem with the stream. Should I leave this PR opened?
> 
> Yes, the pr is not for streaming. Adding support stream=true requires deeper changes in ollama that differentiates tool calls from content, on the radar

thanks for the information. can't wait 👍

**Pull request closed without merging**
