### PR TITLE
[Windows terminal] support colorful ANSI escape code

### PR DESCRIPTION
**Pull request by vinjn**
import "containerd/console" lib to support colorful ANSI escape code

image

### CODE REVIEW

**Comment by dhiltgen** [comment]
@vinjn any chance you could rebase?

**Comment by vinjn** [comment]
@dhiltgen done

**Comment by dhiltgen** [comment]
Thanks for the rebase.

It looks like there's a lint warning.  Could you resolve that by reporting any error returned from the windows console syscall?

**Comment by dhiltgen** [comment]
Note: I'm carrying this commit in #2481 so once that's merged we can close this PR.

**Pull request closed without merging**
