### PR TITLE
Install Ollama with winget

### PR DESCRIPTION
**Pull request by nikiluk**
A tiny update to the readme file, 
linked to https://github.com/ollama/ollama/issues/6298

### CODE REVIEW

**Review by vignesh1507 — APPROVED** [review]
I agree with the changes.

**Comment by mchiang0610** [comment]
Thank you so much for this pull request. This is not the official install flow. The Ollama app on Windows makes the experience better for developers. 

We are hopeful that developers who want to use winget will understand they can use it through it. 

Again, I really appreciate it. 

Thank you

**Comment by xgdgsc** [comment]
Why close? Isn' t it just another way to install the Ollama app?

**Comment by akhial** [comment]
I think there is a misunderstanding, as WinGet is just an easier way to install the Ollama app...

**Pull request closed without merging**
