### PR TITLE
use http.DefaultClient

### PR DESCRIPTION
**Pull request by mxyng**
default client already handles proxy: https://pkg.go.dev/net/http#RoundTripper

### CODE REVIEW

**Review by BruceMacD — APPROVED** [review]
Any suggestions for testing this locally?

**Comment by mxyng** [comment]
> Any suggestions for testing this locally?

The easiest way is to run the mitmproxy docker image, expose 8080 which you set to HTTPS_PROXY. The challenge is it uses a self signed cert so extracting and installing that cert so ollama uses it (without adding it to the system) is kind of annoying. I haven't gotten around to testing this and am blindly trusting the docs

**Comment by eldondevat** [comment]
I can confirm this works with a socks5 proxy now. Thank you!

**Review by jmorganca — APPROVED** [review]
Good cleanup!

**Pull request merged**
