### PR TITLE
add OLLAMA_NOHISTORY to turn off history in interactive mode

### LINKED ISSUE #3002: Disable Chat History/Logging Option
Please add a setting to disable chat history/logging option and consider to have this disabled by default. This can increase privacy from preventing others to see what they asked the AI in the past.

Would especially be useful feature for Users and users management
https://github.com/ollama/ollama/issues/2863

### PR DESCRIPTION
**Pull request by pdevine**
fixes #3002

### CODE REVIEW

**Review by jmorganca — APPROVED** [review]

**Comment by limmy389** [comment]
I'm kinda new to this.... where do I add your code?

**Comment by limmy389** [comment]
how do I add this on a Windows installation?

**Comment by Learning-Gen-AI** [comment]
Add OLLAMA_NOHISTORY where? How do we make this change? Must it be done in every modelfile or is this set centrally, if so where?

**Comment by bbustin** [comment]
@Learning-Gen-AI, from looking at the code, it appears you need to set that as an environment variable prior to running Ollama. Not sure if it is before the `ollama serve` command or the `ollama run __` command...

**Comment by pdevine** [comment]
Hey guys, you can check out the [FAQ](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-configure-ollama-server) which explains how to do this.

**Comment by ImLunaHey** [comment]
@pdevine there's nothing at all in the FAQ about this.

**Pull request merged**
