### PR TITLE
Enable JSON Schema support

### PR DESCRIPTION
**Pull request by hieunguyen1053**
This merge request introduces a new feature that adds support for response_format based on the grammar guide of llama.cpp. This new functionality has been implemented to improve the flexibility of response formats, and it has been tested and works well with both the openai library and langchain.

Please review the code changes and test the feature to confirm compatibility with any additional components or configurations specific to your setup.

Let me know if you need further adjustments!

Screenshot 2024-11-09 at 5 32 06 PM
Screenshot 2024-11-09 at 5 32 48 PM

### CODE REVIEW

**Comment by iscy** [comment]
This patch is modifying the OpenAI compat endpoint but it's not providing an endpoint that is actually compatible with their specs.

**Comment by iscy** [comment]
@hieunguyen1053, could you add this patch to the PR please? The ordered JSON was getting lost within sampling.cpp.

```
diff --git a/llama/sampling.cpp b/llama/sampling.cpp
index 9e1a69e9..4a25cd78 100644
--- a/llama/sampling.cpp
+++ b/llama/sampling.cpp
@@ -250,7 +250,7 @@ struct gpt_sampler * gpt_sampler_init(const struct llama_model * model, const st
         llama_sampler_chain_add(result->chain, llama_sampler_init_greedy());
     }
     if (params.json_schema != "") {
-        nlohmann::json jsonSchema = nlohmann::json::parse(params.json_schema);
+        nlohmann::ordered_json jsonSchema = nlohmann::ordered_json::parse(params.json_schema);
         result->grmr = llama_sampler_init_grammar(model, json_schema_to_grammar(jsonSchema).c_str(), "root");
     } else {
         result->grmr = llama_sampler_init_grammar(model, params.grammar.c_str(), "root");

```

**Comment by hieunguyen1053** [comment]
@iscy  I've added the patch, thanks again for reviewing my request.

**Comment by iscy** [comment]
> @iscy I've added the patch, thanks again for reviewing my request.

You're welcome. I can confirm that the current behavior now matches OAI's specs.

As for the rest of the patch, you should take a look at that documentation:
https://github.com/ollama/ollama/blob/main/llama/README.md#vendoring

By following the vendor's patching structure, you can contain the changes applied to sampling.cpp into its own patch that will be applied when llama.cpp gets updated.

**Comment by hieunguyen1053** [comment]
> > @iscy I've added the patch, thanks again for reviewing my request.
> 
> You're welcome. I can confirm that the current behavior now matches OAI's specs.
> 
> As for the rest of the patch, you should take a look at that documentation: https://github.com/ollama/ollama/blob/main/llama/README.md#vendoring
> 
> By following the vendor's patching structure, you can contain the changes applied to sampling.cpp into its own patch that will be applied when llama.cpp gets updated.

OMG, I didn't see the "do not edit this file" message, can you guide me. I guess I have to commit 2 changes of common.h and sampling.cpp to llama.cpp then change vendoring.env. Is that right?

**Comment by hieunguyen1053** [comment]
I would like to close the PR, it seems that there is a #7900 Structured Output version on Go-lang and it works more stable.

**Comment by ParthSareen** [comment]
Really appreciate all your work @hieunguyen1053 😁

**Pull request closed without merging**
