### PR TITLE
Fix "presence_penalty_penalty" typo, add test.

### PR DESCRIPTION
**Pull request by rick-github**
Fixes: https://github.com/ollama/ollama/issues/6640

### CODE REVIEW

**Review by jmorganca — APPROVED** [review]
Thanks for the fix! Will merge once CI passes.

**Comment by jmorganca** [comment]
@rick-github let me know once this is ready to merge. Thanks again!

**Comment by rick-github** [comment]
@jmorganca good to go, didn't realize the extra formatting requirements

**Comment by defaultsecurity** [comment]
Superb. Thank you for the fix!

**Pull request merged**
