### PR TITLE
Create blogs and tutorials section

### PR DESCRIPTION
**Pull request by FairyTail2000**
This allows for users to get additional usage info outside of the scope of the ollama documentation and for the users to discover additional use cases and How- To's

This would resolve issue #1510

Feedback is appreciated

### CODE REVIEW

**Comment by technovangelist** [comment]
I've just created a community page as a PR for all the tutorials, blogs, and videos that talk about us. When that merges, would be great if you wanted to add the fly link there.

**Comment by FairyTail2000** [comment]
Sure thing, I will hold an eye on to it to see when it is merged

**Comment by iplayfast** [comment]
I've been working hard on exploring ollama will the blog be available to any user?

**Comment by FairyTail2000** [comment]
@iplayfast the proposed section is about including links to other blogs, which should be available to anyone. It would be not so nice to include pay walled blogs or articles

**Comment by mchiang0610** [comment]
thank you for contributing. I think we'll keep the sections minimally for now.

**Pull request closed without merging**
