### PR TITLE
Add support for the ppc64le architecture

### PR DESCRIPTION
**Pull request by mkumatag**
This PR will add the support for [IBM POWER Architecture](https://en.wikipedia.org/wiki/IBM_POWER_architecture).

### CODE REVIEW

**Comment by mkumatag** [comment]
@jmorganca ptal.

**Comment by mkumatag** [comment]
@bmizerany can you please me reviewing this PR?

**Comment by ALutz273** [comment]
There is the project. [https://osuosl.org/](https://osuosl.org/)

This is an open source project that allows you to access IBM Power resources free of charge and compile the software

**Comment by mkumatag** [comment]
> There is the project. https://osuosl.org/
> 
> This is an open source project that allows you to access IBM Power resources free of charge and compile the software

so far, I haven't seen any comments from the maintainers, if infra is the challenge then definitely we can explore and get one for this project.

**Comment by jmorganca** [comment]
Hi @mkumatag thank you for the PR. There isn't immediate plans to support IBM Power architecture in order to make sure Ollama runs reliably on existing platforms. Sorry for the delay in reviewing

**Pull request closed without merging**
