### PR TITLE
fix: use `envconfig.ModelsDir` directly

### PR DESCRIPTION
**Pull request by abitrolly**
This removes noop helper function.

### CODE REVIEW

**Review by maaslalani — APPROVED** [review]

**Comment by abitrolly** [comment]
@maaslalani got back the error check for empty model dir. Otherwise it would create models in current directory if user home is not found for some reason.

**Comment by maaslalani** [comment]
> Can we please get this merged in? The ability to set the models dir is very important.

Fwiw, you can already set the `OLLAMA_MODELS` directory, this is just a refactor to use the established `envconfig` pattern.

**Comment by maaslalani** [comment]
> It worked for me after I deleted everything inside the old ollama folder, with the exceptions of the keys (id_ed25519)

This PR solves the `id_ed25519` keys location: https://github.com/ollama/ollama/pull/4656

**Comment by abitrolly** [comment]
@jmorganca hi Jeffrey. Any chance to get this merged?

**Comment by abitrolly** [comment]
Good news - @pdevine made the same changes in - https://github.com/ollama/ollama/pull/5029

@maaslalani our code is probably too bogus to deserve attention. :D

I am going to solve conflict here and see if there is something left.

**Comment by abitrolly** [comment]
After #5029 only a minor cleanup left. Rebased.

**Comment by pdevine** [comment]
@abitrolly yeah, the reason why this didn't get moved into envconfig initially was because there were issues w/ the unit tests failing. My last change fixed that as well too. I think we can go ahead and close this PR?

**Comment by abitrolly** [comment]
@pdevine there is still one cleanup left here. Take a look at the diff.

**Review by pdevine — APPROVED** [review]

**Pull request merged**
