### PR TITLE
feat: K/V cache quantisation (massive vRAM improvement!)

### PR DESCRIPTION
**Pull request by sammcj**
This PR introduces optional K/V (context) cache quantisation.

In addition the deprecated `F16KV` parameter has been removed, if a user wishes for some reason to run the KV at f32, they can provide that as an option.

## Impact

- With defaults (f16) - none, behaviour is the same as the current defaults.
- With q8_0
	- **The K/V context cache will consume 1/2 the vRAM** (!)
	- A _very_ small loss in quality within the cache
- With q4_0
	- **the K/V context cache will consume 1/4 the vRAM** (!!)
	- A small/medium loss in quality within the cache
	- For example, loading llama3.1 8b with a 32K context drops vRAM usage by cache from 4GB to 1.1GB 
- The and q4_1 -> q5_1 in between.

Additional quantisations supported by llama.cpp and this PR that may depend on the quantisation of the model you're running:

`q5_1`, `q5_0`, `q4_1`, `iq4_nl`

- Fixes https://github.com/ollama/ollama/issues/5091
- Related discussion in llama.cpp - https://github.com/ggerganov/llama.cpp/discussions/5932
	- (Note that ExllamaV2 has a similar feature - https://github.com/turboderp/exllamav2/blob/master/doc/qcache_eval.md)

## Screenshots

Example of estimated (v)RAM savings - f16 (q8_0,q4_0)

image

### f16

kv_cache_f16

### q4_0

kv_cache_q4_0

### q8_0

kv_cache_q8_0

## Performance

llama.cpp did some perplexity measurements (although looking at the commits things have likely improved even further since May when they were done, and CUDA graphs were later fixed etc....): https://github.com/ggerganov/llama.cpp/pull/7412#issuecomment-2120427347

As far as I can tell (at least with q6_k quants) there isn't much of a noticeable hit to performance.

### CODE REVIEW

**Comment by sammcj** [comment]
Missed one place where I need to add the env var sourcing... adding that now won't be long.

**Comment by sammcj** [comment]
env var parsing logic improved, I've tested a few different sceneries and parameter combinations 👍 😄

**Comment by sammcj** [comment]
## llama-3.1-70b-q4_k_m 

### q4_0 K/V cache:

16K context size uses 1.44GB:

```
llama_new_context_with_model: n_ctx      = 16384
llama_new_context_with_model: n_batch    = 512
llama_new_context_with_model: n_ubatch   = 512

llama_new_context_with_model: KV self size  = 1440.00 MiB, K (q4_0):  720.00 MiB, V (q4_0):  720.00 MiB
```

32K context size uses 2.88GB:

```
llama_new_context_with_model: n_ctx      = 32768
llama_new_context_with_model: n_batch    = 512
llama_new_context_with_model: n_ubatch   = 512

llama_new_context_with_model: KV self size  = 2880.00 MiB, K (q4_0): 1440.00 MiB, V (q4_0): 1440.00 MiB
```

### q8_0 K/V cache:

16K context size uses 2.72GB:

```
llama_new_context_with_model: n_ctx      = 16384
llama_new_context_with_model: n_batch    = 512
llama_new_context_with_model: n_ubatch   = 512

llama_new_context_with_model: KV self size  = 2720.00 MiB, K (q8_0): 1360.00 MiB, V (q8_0): 1360.00 MiB
```

32K context size uses 5.44GB:

```
llama_new_context_with_model: n_ctx      = 32768
llama_new_context_with_model: n_batch    = 512
llama_new_context_with_model: n_ubatch   = 512

llama_new_context_with_model: KV self size  = 5440.00 MiB, K (q8_0): 2720.00 MiB, V (q8_0): 2720.00 MiB
```

**Comment by AncientMystic** [comment]
Great work 👍 i can't wait to see this in the next release.

**Comment by sammcj** [comment]
Been running q8_0 K and V for the past day - it's been working great and now I can run some decent context sizes with 70b models :D

**Comment by sammcj** [comment]
> @AncientMystic Great work 👍

Thanks, really the credit should go to llama.cpp though, I've just added the ability to make use of it.

> I can't wait to see this in the next release.

The project currently almost 300 unmerged PRs (🤯) so there is every chance this might end up getting lost in a sea of noise so to speak.

**Comment by AncientMystic** [comment]
> > @AncientMystic Great work 👍
> 
> 
> 
> Thanks, really the credit should go to llama.cpp though, I've just added the ability to make use of it.
> 
> 
> 
> > I can't wait to see this in the next release.
> 
> 
> 
> The project currently almost 300 unmerged PRs (🤯) and it's not obvious how PRs are prioritised so there is every chance this might end up getting lost in a sea of noise so to speak.

I hope it doesn't get lost in all the unmerged PRs, i think this is quite possibly one of the biggest improvements we could ask for currently

**Comment by sammcj** [comment]
> i think this is quite possibly one of the biggest improvements we could ask for currently

Personally I agree, this and and support for speculative decoding (draft models) #5800 are the two things that are incredibly helpful in ExllamaV2/TabbyAPI - but once they're enabled in Ollama I don't really have any reason to use exl2 anymore.

**Comment by AncientMystic** [comment]
> > i think this is quite possibly one of the biggest improvements we could ask for currently
> 
> 
> 
> Personally I agree, this and and support for speculative decoding (draft models) #5800 are the two things that are incredibly helpful in ExllamaV2/TabbyAPI - but once they're enabled in Ollama I don't really have any reason to use exl2 anymore.

Maybe you can request a review or we can tag the devs or something to bring attention to this and get it merged. 

I would love to see this added soon, many of us (probably most of us) do not have ultra expensive GPUs with massive amounts of vram, so this update is crucial for most everyone out there running ollama on consumer/older hardware.

**Comment by sammcj** [comment]
I did start a thread on their discord and tried pinging one of the devs there but no bites. I get the feeling that prioritisation must be done somewhere offline and what might be important for us isn’t so much for the maintainers (which I get in a way).

**Comment by AncientMystic** [comment]
> I did start a thread on their discord and tried pinging one of the devs there but no bites. I get the feeling that prioritisation must be done somewhere offline and what might be important for us isn’t so much for the maintainers (which I get in a way). 

It is probably another non public group or something just for the devs to collaborate and they likely prioritise fixes and stability over new features since new features can introduce more problems / complications to everything, ollama seems to be progressing quickly enough though and there seems to be at least a fairly decent balance to fixes and new features, so hopefully it can be added soon.

**Comment by sammcj** [comment]
I don’t really like to ping people directly but @jmorganca might be one for you to be aware of so it doesn’t get lost in the noise.

**Review by atelepov — APPROVED** [review]

**Review by atelepov — APPROVED** [review]

**Comment by justinh-rahb** [comment]
👀 guys this is amazing, this would really help the folks with consumer GPUs. We get a lot of Open WebUI users confused their brand new Lllama 3.1 isn't performing up to the expectations of its new context size because they're unaware it doesn't run that by default, nor do they have the memory to do so, would be nice to have an actual "solution" we can give them.

**Comment by AncientMystic** [comment]
> 👀 guys this is amazing, this would really help the folks with consumer GPUs. We get a lot of Open WebUI users confused their brand new Lllama 3.1 isn't performing up to the expectations of its new context size because they're unaware it doesn't run that by default, nor do they have the memory to do so, would be nice to have an actual "solution" we can give them.

This would help fix so many problems and help with running so many models, i cannot wait to see it pushed through, i already have my environment variables setup and ready for it. 

My GPU is only 8GB plus theres the fact pascals (which seem to be what MANY people are using) have absolutely abysmal F16 performance, which is the default for KV cache. 

So hopefully this also can maybe improve performance a bit, it would make sense that it does if only because of reducing memory usage by so much. 

Either way this will be an amazing addition to Ollama and i hope the devs can get this committed and into one of the upcoming releases ASAP, we need this.

**Comment by justinh-rahb** [comment]
> Either way this will be an amazing addition to Ollama and i hope the devs can get this committed and into one of the upcoming releases ASAP, we need this.

Yes, hopefully it does away with this meme 🤣

i_like_big_ctx_and_i_cannot_lie

**Comment by AncientMystic** [comment]
> > Either way this will be an amazing addition to Ollama and i hope the devs can get this committed and into one of the upcoming releases ASAP, we need this.
> 
> 
> 
> Yes, hopefully it does away with this meme 🤣
> 
> 
> 
> i_like_big_ctx_and_i_cannot_lie
> 
> 
> 
> 

Yes, hopefully haha 

It will make it possible for everyone to run better models like the 13b-70b on lower end hardware too (with basic context sizes anyways) 

There are many pretty decent models in the 7b-13b range that would also run very well with high context

Plus theres always low end hardware to think about or use cases where someone doesn't want to dedicate the whole gpu to Ollama 

Many 7b models could be ran in 1.5-3gb with a lower KV quant, that would REALLY help everyone with 2gb, 3gb and 4gb gpus have access to Ollama which are probably some of the most common and that would allow them to even use a half decent context size.

This addition can really help make Ollama accessible to everyone.

**Comment by Earnest-Williams** [comment]
Absolutely brilliant. This is genuinely needed.

**Comment by sammcj** [comment]
I haven't seen any interest in this from Ollama, I'm wondering if they have something else planned?

**Comment by jmorganca** [comment]
@sammcj this is really cool! Thanks. I remember seeing q4_0 kv caches crash with popular models such as llama2/llama3– do you know if that's still the case?

**Comment by AncientMystic** [comment]
> I haven't seen any interest in this from Ollama, I'm wondering if they have something else planned?

I hope they will add it soon, it would certainly be a real shame if they passed over such a wonderful opportunity to improve the software so greatly, I couldn't see them ignoring this PR for sure, probably just haven't gotten to it quite yet with all the work that must be done on a project like this.

**Comment by sammcj** [comment]
@jmorganca, hey 👋 , thanks for taking a look!

I've been running q8_0 with Llama 3.1, DeepSeek Coder V2 Lite, Codestral and Nemo for the past week, I checked that q4_0 works but I haven't evaluated it's quality, I'm assuming that'd be an issue to log in the llama.cpp project if it does occur - and for Ollama it would just mean not enabling or recommending it by default.

**Comment by sammcj** [comment]
The latest rebase from main has resulted in failing builds, I probably need to dig into what changed upstream in the past week to figure out where the issue is now.

**Comment by sammcj** [comment]
Oh I see what's happened, it seems llama.cpp submodule got a bump and made it into my PR, willfix!

**Comment by sammcj** [comment]
fixed :)

**Comment by sammcj** [comment]
Looks like there were more merge conflicts from upstream over night, currently resolving them and will push and update shortly.

**Comment by sammcj** [comment]
Rebased and fixed conflicts, not sure why the "windows-2019" test is failing, I don't have any windows machines to test that.

**Comment by AncientMystic** [comment]
> Rebased and fixed conflicts, not sure why the "windows-2019" test is failing, I don't have any windows machines to test that.

Line 308-309 and 1122-1126 seem to be describing it erroring on runner location.

**Comment by sammcj** [comment]
> Line 308-309 and 1122-1126 seem to be describing it erroring on runner location.

I don't think it was related to this PR at all, rerunning the job fixed it.

**Comment by sammcj** [comment]
Looks like upstream changes have broken this again, I'll have to look into it and rework again 🫤

**Comment by sammcj** [comment]
It looks to now be broken by changes to the linters and formatters that were introduced yesterday in https://github.com/ollama/ollama/pull/6128.

They don't seem to annotate the PR with any errors and looking through the build logs the new linter fails with an unhelpful error messages: `File is not 'gci'-ed with --skip-generated -s standard -s default -s localmodule (gci)`

Perhaps I'm misunderstanding this but when I run golangci-lint with those flags - they're not even valid flags?

```
golangci-lint --skip-generated -s standard -s default -s localmodule                                                  (feature/kv-quant-lint)
Error: unknown flag: --skip-generated
Usage:
  golangci-lint [flags]
  golangci-lint [command]

Available Commands:
  cache       Cache control and information
  completion  Generate the autocompletion script for the specified shell
  config      Config file information
  custom      Build a version of golangci-lint with custom linters
  help        Help
  linters     List current linters configuration
  run         Run the linters
  version     Version

Flags:
      --color string   Use color when printing; can be 'always', 'auto', or 'never' (default "auto")
  -h, --help           Help for a command
  -v, --verbose        Verbose output
      --version        Print version

Use "golangci-lint [command] --help" for more information about a command.

Failed executing command with error: unknown flag: --skip-generated
```

SCR-20240803-ogly

I'd really like to see this (or another solution to the same effect) merged in, but the slow feedback cycles when trying to contribute to the project make it quite difficult to keep any momentum up between merge conflicts and frequent rebasing.

**Comment by AncientMystic** [comment]
This is really sad to see ☹️

**Comment by sammcj** [comment]
Alright think I've got it aligned with the new linting requirements and linting/tests are passing again.

@jmorganca anything I can do to help get this reviewed?

**Comment by AncientMystic** [comment]
Maybe dhiltgen can help or another member of the ollama team, dhiltgen seems pretty active. 

There has to be something that can be done to help get this feature added.

**Comment by sammcj** [comment]
I see there’s conflicts with changes upstream again.

It doesn’t seem like this is something Ollama is interested in, I’m thinking it’s probably easier to use llama.cpp directly or ExllamaV2 w/ TabbyAPI for performance / efficiency gains moving forward.

**Comment by AncientMystic** [comment]
> I see there’s conflicts with changes upstream again.
> 
> 
> 
> It doesn’t seem like this is something Ollama is interested in, I’m thinking it’s probably easier to use llama.cpp directly or ExllamaV2 w/ TabbyAPI for performance / efficiency gains moving forward.

Sad to see, ive been reading through some of the open PRs and it seems there are quite a few good ones for support and performance lingering for quite some time. 

I guess i should probably give Llamap.cpp and ExLlamaV2 a try, i only have a tesla p4 8gb and an intel arc A310 4gb at the moment so i can't exactly afford not to have features like this especially when the arc card isn't even supported yet an that PR is sitting open too.

**Comment by sammcj** [comment]
The latest merge conflict wasn't at all bad, fixed that up again now.

**Comment by sammcj** [comment]
Hey @dhiltgen 👋, I was wondering if you might have any input on what I might need to do to help get reviewed?

**Comment by oberdfr** [comment]
please get this merged. it would help a lot of people that doesnt have top tier hardware....

**Comment by AncientMystic** [comment]
> please get this merged. it would help a lot of people that doesnt have top tier hardware....
> 
> anyway @sammcj i tried to build your fork, buw hen i /set parameters the cache always remains fp16:
> 
> >>> /set parameter cache_type_v q4_0
> 
> Set parameter 'cache_type_v' to 'q4_0'
> 
> >>> /set parameter cache_type_k q4_0
> 
> Set parameter 'cache_type_k' to 'q4_0'
> 
> >>> /set parameter num_ctx 32768
> 
> 
> 
> but still
> 
> llama_kv_cache_init:      CUDA0 KV buffer size =  4096.00 MiB
> 
> llama_new_context_with_model: KV self size  = 4096.00 MiB, K (f16): 2048.00 MiB, V (f16): 2048.00 MiB
> 
> 
> 
> any idea about what im doing wrong?
> 
> 

I tried too, even grabbed the prebuilt files off here and threw them into the right folders / disabled gpu just as a cpu only test run on avx2, still reported f16 with the same memory usage. 

I would really like to see this added too, other projects are supporting it and it looks like it has really great results

with ollama being more so a friendly wrapper for llama.cpp, maximum performance and support for consumer hardware should really be a top priority, since that is really the biggest audience it appeals to, many people who have the highest tier hardware are developers and that isn't really the audience an easy to use executable wrapper appeals to.... but it isn't like there are downsides to optional performance features except maintenance maybe.

**Comment by pmarcelll** [comment]
Hey @sammcj, I tried this code locally, and while the `KV self size` is correct (it's set to q8_0 with env vars for both), the `cacheType` parameter value in `estimateKvCacheSize` is always an empty string (verified with extra debug messages), so the final estimated size will be overestimated with the default fp16 type and it will still allocate a couple of layers on the CPU.

**Comment by sammcj** [comment]
Thanks for testing it out @pmarcelll! Good catch with the estimations, I'll take a look at that hopefully today some time.

**Comment by AncientMystic** [comment]
I just tried the latest commit, since the windows binaries were not listed I attempted a manual build and it seems to hang on generating code, so pretty sure either something is wrong with my test setup or I managed to do something wrong lol (not use to compiling ollama or binaries in general on anything other than linux) 

i will give it another try tomorrow and report back

**Comment by sammcj** [comment]
@pmarcelll after a _lot_ of debugging I think I've figured it out, I hadn't touched Ollama's scheduler code before so there was quite a bit of learning to do 😅 

I'll clean up the code now and do a proper test, then I'll make the PR as non-draft once it's good to try again.

**Comment by sammcj** [comment]
What the heck github, I rebased my branch and it closed the PR without an option to re-open it!

image

**Comment by sammcj** [comment]
OK after adding that comment it's now letting me 🤣 nice one MS.

**Comment by sammcj** [comment]
.

**Comment by sammcj** [comment]
OK so it looks like someone has merged in a bunch of files with borked line endings to the main ollama repo, it was causing all sorts of chaos when trying to add only my changes in.

This PR is moving to https://github.com/ollama/ollama/pull/6279 as Github won't let me re-open it for some reason.

image

**Pull request closed without merging**
