### PR TITLE
Add OpenAI compatible API chat completions

### PR DESCRIPTION
**Pull request by vaayne**
fix for issue https://github.com/jmorganca/ollama/issues/305

## API example
image

## Stream Response
image

### CODE REVIEW

**Comment by Vaayne** [comment]
Hello @jmorganca, I hope this PR is helpful. We can utilize `/chat/completions/` with a variety of existing tools.

**Comment by Vaayne** [comment]
> Hi @Vaayne thanks for the contribution, I've been working on this for the past couple of days too (my bad, should have assigned myself the issue). If it's ok with you I'd like to cherry-pick your changes here and add the new `/chat` endpoint logic that we are working on top of them. We are gonna add proxy endpoints as separate logic. That way we can avoid the repeating work but both be on the commit.

Hi. It's nice to know you're working on chat API, feel free to cherry-pick the code.

**Comment by Vaayne** [comment]
@BruceMacD I've noticed the Chat API, but it doesn't seem to be fully compatible with the OpenAI chat completions API in terms of both streaming and nonstreaming response. Are you planning to address this issue, or will it remain unchanged?

**Comment by Vaayne** [comment]
@BruceMacD I believe it's crucial to be compatible with the OpenAI Chat Completions API. This ensures that we can leverage all the existing tools that have already integrated with OpenAI. The llama.cpp codebase already includes these APIs.

https://github.com/ggerganov/llama.cpp/issues/4216

**Comment by restlessronin** [comment]
@BruceMacD is this branch up to date? https://github.com/jmorganca/ollama/compare/main...brucemacd/openai-chat

Would you like some help with it? This is a great project and I feel that a built-in openai api proxy (even for just chat completion) would be a big win.

**Comment by hugo53** [comment]
Will we merge this PR @BruceMacD? OpenAI compatible API is really helpful for lots of applications.

**Comment by jmorganca** [comment]
Hi @vaayne, thank you so much for writing this PR. This has since been added to the api under `/v1/chat/completions`. We decided to end up going with a middleware approach. I wanted to apologize for not doing a better job of coordinating with you to get this change in sooner, since I can tell from the diff you put in quite a bit of work, something we'll work on in future PRs. Thanks so much again and sorry about that.

**Comment by who0sy** [comment]
@vaayne Hey, buddy, your terminal is really beautiful. Can you tell me its name?

**Comment by vaayne** [comment]
> @vaayne Hey, buddy, your terminal is really beautiful. Can you tell me its name?

@who0sy here is my dotfiles https://github.com/vaayne/dotfiles

**Pull request closed without merging**
