### PR TITLE
Community Integration: PromptingTools.jl

### PR DESCRIPTION
**Pull request by svilupp**
First of all, thank you for the awesome library!

I was wondering if you would consider adding a link to PromptingTools.jl, a Julia library that has had an integration with Ollama since its early days.

### CODE REVIEW

**Review by jmorganca — APPROVED** [review]
Thank you! Sorry this took so long to review.

**Comment by jmorganca** [comment]
Would it be possible to rebase?

**Comment by svilupp** [comment]
@jmorganca, of course! I've just rebased.

**Comment by svilupp** [comment]
@jmorganca gentle reminder before the PR gets out of sync. Let me know if you have any feedback/requests on the text.

**Review by jmorganca — APPROVED** [review]

**Comment by jmorganca** [comment]
Thank you! Needs one more rebase

**Comment by svilupp** [comment]
@jmorganca done!

**Comment by jmorganca** [comment]
Thanks!

**Pull request merged**
