### PR TITLE
Adding Aide to the list of desktop apps

### PR DESCRIPTION
**Pull request by theskcd**
Hi all! We added support for running local models in the editor using Ollama, would love to show that Aide is supported on the README

### CODE REVIEW

**Comment by jmorganca** [comment]
Hi there, is there a link to the repo/project? Thanks!

**Comment by mchiang0610** [comment]
closing because it links to an org page.

**Comment by mchiang0610** [comment]
Sorry, let me know if there is a project page to link to. Really appreciate the integration!!! Can't wait for more.

**Comment by theskcd** [comment]
Hey @mchiang0610 ! I see what you mean haha, so its not open source (which I assume is what you guys are showcasing on the github page) let me know if that's not the case.
Either ways I do love ollama and planning on using it a lot more in our editor! its great 🤩

**Pull request closed without merging**
