### PR TITLE
style: status badge for `test` in `README.md`

### PR DESCRIPTION
**Pull request by hamirmahal**

### CODE REVIEW

**Comment by hamirmahal** [comment]
# Without this change

image

# With this change

image

**Comment by jmorganca** [comment]
Hi @hamirmahal thanks for the PR! For build status it might be better for us to just use the build status in the commit header of the repo viewer, for example:
Screenshot 2024-05-09 at 9 08 29 AM

**Comment by hamirmahal** [comment]
You're welcome, @jmorganca.

**Comment by hamirmahal** [comment]
Badges can be useful because they let potential contributors instantly see which checks in a repository are passing and failing, and where they should focus their attention, without having to click anything. They also make a `README` more enjoyable to look at, in my opinion. I'll delete the branch if I don't hear back from you in the next few days.

**Pull request closed without merging**
