### PR TITLE
Streamlined server startup and fixed model loading status

### PR DESCRIPTION
**Pull request by mann1x**
This patch provides:
- Streamlined WaitUntilRunning method without ticker and nested loop
- Updated server.cpp with the correct startup sequence; the HTTP server starts listening before loading the model and thus the `model loading` status is correctly reported, the `/health` API endpoint is excluded as well from the server logging

### CODE REVIEW

**Comment by Lucas-BLP** [comment]
hi, looking forward for this fix in the release, loading status appears indeed to be corrupted sometimes

**Comment by mann1x** [comment]
@dhiltgen 
Would you look at this?

**Comment by dhiltgen** [comment]
Thanks for putting this together @mann1x !

I've carried your commits in #4294 and added some additional fixes for a recent regression that snuck in.

**Comment by mann1x** [comment]
@dhiltgen perfect, thanks!

**Pull request closed without merging**
