### PR TITLE
update readme description

### PR DESCRIPTION
**Pull request by reid41**
add some introduction about the project

### CODE REVIEW

**Review by WolfTheDeveloper — CHANGES_REQUESTED** [review]
If you are going to add a description to one of the community projects, you might as well add a description to all the projects.

**Comment by reid41** [comment]
@WolfTheDeveloper done

**Review by WolfTheDeveloper — APPROVED** [review]

**Comment by jmorganca** [comment]
Thanks for the PR. It would be better for the specific authors of the projects to do this (just to avoid confusion). For now would it be possible to edit the project you've added? Thanks! Also don't forget to rebase 😊

**Comment by reid41** [comment]
@jmorganca got it, and seems close it by accident, could you please help to merge [PR 4303](https://github.com/ollama/ollama/pull/4303)

**Pull request closed without merging**
