### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AshD**
Adding info on Fusion Quill. Setup info is here https://fusionquill.ai/help-setup-ollama/

Fusion Quill Personal Edition is a Windows app on the Microsoft App Store that connects to multiple AI models with workflows and UX like an Integrated Word processor with AI Chat in a split-pane UI that enables creating documents with ease!

Fusion Quill Personal Edition supports

AI Writing Buddy with Multiple AIs like Ollama, OpenAI, Mistral, Azure AI, Google Gemini, Bedrock, vLLM, etc. Chat with a Debate Coach, Interview Coach and other assistants. More info at https://FusionQuill.AI

### CODE REVIEW

**Comment by AshD** [comment]
Let me know if you need any more info. You can download the Fusion Quill Windows app from the Microsoft store below
https://www.microsoft.com/store/r/9P6W2WLP0ZKL

**Review by mchiang0610 — APPROVED** [review]

**Comment by jmorganca** [comment]
Possible to rebase? Thanks!

**Comment by mrdjohnson** [comment]
In the hopes of offloading some of the PR time for the devs here, another active discord member and I are making an "awesome ollama" list, I took the liberty of adding this project as well! (it will not affect the PR here, just letting you know)

https://github.com/endo9000/Awesome-Ollama?tab=readme-ov-file#web--desktop-uis

**Comment by mchiang0610** [comment]
thank you so much for submitting this. I'm trying to keep this around community based projects right now. I really appreciate it though. 

The awesome list above is awesome! Thank you

**Pull request closed without merging**
