### PR TITLE
Support customized CPU flags for runners

### LINKED ISSUE #2187: illegal instruction in cuda runner
```
2024/01/25 10:14:54 cpu_common.go:18: INFO CPU does not have vector extensions
loading library /tmp/ollama1758121582/cuda_v11/libext_server.so
SIGILL: illegal instruction
```

@dhiltgen this will be of interest to you

### LINKED ISSUE #2205: Support additional AVX instruction sets
I have a intel CPU that supports a number of AVX features, but most of them are not picked up when using ollama.  Below is the llama.log file:

system info: AVX = 1 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 0 | ARM_FMA = 0 | F16C = 0 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | 

However, when I look at lscpu, I see that avx512 and avx512_vnni are actually supported.

I'm running on Manjaro Linux with Ollama installed from official repos.  It's an Intel Core i7-1065G7 with Iris Plus G7 onboard iGPU. (the iGPU works very well with ncnn vulkan inference)

### LINKED ISSUE #2281: Support GPU runners with AVX2
I am running ollama on i7-14700K, which supports AVX2 and AVX_VNNI, and a GeForce RTX 1060.

After reading #2205, I enable `OLLAMA_DEBUG=1` to check if ollama utilize AVX2 of this CPU. But unlike that one, I couldn't get ollama to use AVX2. The debug message has:
```
time=2024-01-30T12:27:26.016-05:00 level=INFO source=/tmp/ollama/gpu/gpu.go:146 msg="CUDA Compute Capability detected: 6.1"
time=2024-01-30T12:27:26.016-05:00 level=INFO source=/tmp/ollama/gpu/cpu_common.go:11 msg="CPU has AVX2"
loading library /tmp/ollama1660685050/cuda_v12/libext_server.so
time=2024-01-30T12:27:26.032-05:00 level=INFO source=/tmp/ollama/llm/dyn_ext_server.go:90 msg="Loading Dynamic llm server: /tmp/ollama1660685050/cuda_v12/libext_server.so"
time=2024-01-30T12:27:26.032-05:00 level=INFO source=/tmp/ollama/llm/dyn_ext_server.go:145 msg="Initializing llama server"
[1706635646] system info: AVX = 1 | AVX_VNNI = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 0 | ARM_FMA = 0 | F16C = 0 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 |
[1706635646] Performing pre-initialization of GPU
ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   yes
ggml_init_cublas: CUDA_USE_TENSOR_CORES: no
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce GTX 1060 3GB, compute capability 6.1, VMM: yes
```

Thus ollama does detect GPU and also reports `CPU has AVX2`. However, when initializing server, it shows `AVX2 = 0` as well as `AVX_VNNI = 0`.

I also follow [here](https://github.com/ollama/ollama/blob/main/docs/development.md), setting `OLLAMA_CUSTOM_CPU_DEFS="-DLLAMA_AVX=on -DLLAMA_AVX2=on -DLLAMA_F16C=on -DLLAMA_FMA=on"`, to build the binary locally with AVX2 support. However, the result is the same as the released binary, and I still get `AVX_VNNI = 0 | AVX2 = 0`. How can I make ollama use AVX2 in my CPU?

### LINKED ISSUE #7457: Adding avx2+avx512 to cuda runner in new ollama code
In the old code i added avx2+512 in the gen_windows.ps1 by simply adding DGGML_AVX2=on & DGGML_AVX512=on after the DGGML_AVX=on line in the cuda build function

It added a fairly decent performance boost 

I have added avx512 to cpu, But In the new code i cannot seem to find where to properly add it in the make files to also add it to cuda 

What do i need to change on what lines in which files to add this to the new ollama code?

### PR DESCRIPTION
**Pull request by dhiltgen**
This implements a simplified custom CPU flags pattern for the runners. When built without overrides, the runner name contains the vector flag we check for (AVX) to ensure we don't try to run on unsupported systems and crash.  If the user builds a customized set, we omit the naming scheme and don't check for compatibility.  This avoids checking requirements at runtime, so that logic has been removed as well.  This can be used to build GPU runners with no vector flags, or CPU/GPU runners with additional flags (e.g. AVX512) enabled.

This also cleans up some variables that were stale from the recent Go server change, as well as a few duplicate definitions from prior branch merges.

Fixes #2187
Fixes #2205
Fixes #2281 
Fixes #7457

### CODE REVIEW

**Comment by fxmbsw7** [comment]
i suggest a var alike enable disable checkment
btw will it support arm64 avx and neon64 ?

**Comment by AncientMystic** [comment]
Thank you very much, added in and compiled. Verified this does indeed fix #7457

**Comment by fxmbsw7** [comment]
sorry how to use / test ? im not experienced with the git stuff and else ...

**Comment by sammcj** [comment]
Glad to see this making a comeback, avx512 gives a noticeable boost for Ryzen CPUs :)

**Comment by dhiltgen** [comment]
This is now carried in #7499

**Pull request closed without merging**
