### PR TITLE
Speech Prototype

### PR DESCRIPTION
**Pull request by royjhan**
whisper.cpp - custom ggml, wav audio

Instructions for running in md

As of now would require conversion to ggml format to run inference, would wait to see the general momentum surrounding speech-to-text models as bigger players release foundational models.

### CODE REVIEW

**Comment by pratikkabade** [comment]
hi @royjhan have you ever used neo4j as a database to store and retieve embeddings for ollama?

if so can you help me out?

**Comment by royjhan** [comment]
https://github.com/user-attachments/assets/e66c97d7-e42d-48a8-8d89-d4b01f6f4834

Basic Demo, please leave feedback anyone!

**Comment by lasseedfast** [comment]
This sounds and looks super promising, any news?

**Comment by mchiang0610** [comment]
Closing this for now since we will be making new PRs to support voice.

**Comment by dmikushin** [comment]
@mchiang0610 , please mention the specific new PRs to support voice here.

**Comment by CrazyBoyM** [comment]
@mchiang0610 where is the PR for asr and tts?

**Pull request closed without merging**
