### PR TITLE
Adding Cross-Origin Support for Web Apps

### PR DESCRIPTION
**Pull request by Nols1000**
This pull request introduces a new feature that allows users to grant cross-origin access to web applications. This will allow easier setup for web applications that would like to access the local Ollama API.

Changes Made:
- Added an endpoint that allows web applications to request using the local Ollama API
  - The user is prompted for consent
- Added an endpoint to view all authorizations
- Added an endpoint to revoke an authorization
- Updated documentation to provide clear instructions on configuring cross-origin access for web applications.

Address:  #433 #300

Screenshot:
OpenSuse - Gnome (Linux): 
Screenshot from 2023-12-03 03-38-10

MacOS:
image

### CODE REVIEW

**Comment by chadgauth** [comment]
I need this myself, came here to see what's going on with this functionality!

**Comment by luckydonald** [comment]
I feel like this could lock up your gui if that api endpoint gets spammed?

**Comment by Nols1000** [comment]
Thanks for the comment @luckydonald,
To mitigate that risk somewhat I've added the "Block"-Option, but if a malicious was to spam the endpoint with different origins that would be a problem. 
If the electron app had more features and would be delivered on Linux, it might be better to create a settings page with a list of all requests, so the spam wouldn't always produce a popup.
Another option to mitigate spam I can think of would be to verify the request by sending a get request to a tbd ".well-known" address a confirming a nonce provided before. This option would need some more refinement.

**Comment by luckydonald** [comment]
One idea would be to at least disallow other prompt while one is still open, or add it to a (checkbox?) list in that very prompt.
That way you at least never can't end up with 300 dialog boxes stacked over each other.
Other than that, I don't see it really as something to fix critically.

I'd rather would like to think about the naming of that endpoint, as it conflicts with what you would normally expect there, some kind of user:password auth. My personal thought would be something along the lines of `PUT /api/cross_origin`. Could you show the payload for this? I assume you somehow can set the hostname, or is that taken from the `Referer` field?

Another thing I would think about is how this works with unattended systems.
The `ollama origin add https://example.com` in #300 could be benefficial here, and maybe there could even be a
`ollama origin allow none` / `ollama origin allow listed` / `ollama origin allow all`  could globally turn it off or allow all of the domains.

**Comment by DevChrisRoth** [comment]
Hey guys,
overall I believe it would be nice to have a small minimalistic GUI where you can see your logs, downloaded models and configuration options for example like CORS or defined system variables. 
Maybe the GUI is a separate application, where you can connect to the original service client.

What do you guys think about it? Is something similar already in progress?

**Review by nathanzilgo — APPROVED** [review]

**Comment by Nols1000** [comment]
Thanks for all the interest in this PR, but I wont resolve the conflicts or put in any more work without interest of the maintainers, because it seems like this PR won't be merged. Feel free to fork and fix the problem with Denial of Service (by Popup) and naming, etc. @luckydonald has some good ideas there.

**Pull request closed without merging**
