### PR TITLE
Make new tokenizer logic conditional

### PR DESCRIPTION
**Pull request by dhiltgen**
Only use the new cgo tokenizer/detokenizer if we're using the new runners

### CODE REVIEW

**Review by jmorganca — APPROVED** [review]

**Review by jessegross — APPROVED** [review]

**Comment by jmorganca** [comment]
Something happened with CI on this one..

**Comment by jessegross** [comment]
The CI issue is due to the new version of Go having stricter lint checks. I cherry picked 2697d7f5 from main to jmorganca/llama to fix these PRs after they are rebased

**Comment by mxyng** [comment]
go should not have been upgraded automatically. the branch is missing https://github.com/ollama/ollama/pull/6343 which pins go version to go.mod's version, 1.22.5 currently

**Comment by dhiltgen** [comment]
Rebased to clean things up.

**Pull request merged**
