### PR TITLE
update llama.cpp submodule to `12247f4` (release tag: b2440)

### PR DESCRIPTION
**Pull request by acanis**
Adding support for Command-R model #3100

### CODE REVIEW

**Comment by acanis** [comment]
Tested with the Command-R Q2_K model here: https://ollama.com/andrewcanis/command-r:q2_K
```
./ollama run andrewcanis/command-r:q2_K
>>> Hello, how are you?
Good day. I'm doing well, thank you for asking! How can I help you today?

I'm ready to assist you; feel free to ask any questions or discuss anything you'd like to explore. Have a wonderful day and enjoy the conversation!

>>> what's 1+1?
The sum of 1 + 1 is simply 2.
```

**Comment by AShabana** [comment]
I get this error 
Error: exception error loading model architecture: unknown model architecture: 'command-r'

While run 
ollama run andrewcanis/command-r:q2_K 'hi'

**Comment by acanis** [comment]
@AShabana you need to recompile with this PR first to get the latest version of llama.cpp (with Command-R support) and then launch the updated ollama server:
```
git clone https://github.com/acanis/ollama ollama
cd ollama
go generate ./...
go build .
./ollama serve
```

**Comment by simsi-andy** [comment]
Could you also upload the q8 version? ✌🏻💫

**Comment by acanis** [comment]
I've added the following quantizations:
```
	../ollama/ollama run andrewcanis/command-r:q2_K 'hi'
	../ollama/ollama run andrewcanis/command-r:q3_K_L 'hi'
	../ollama/ollama run andrewcanis/command-r:q3_K_M 'hi'
	../ollama/ollama run andrewcanis/command-r:q3_K_S 'hi'
	../ollama/ollama run andrewcanis/command-r:q4_0 'hi'
	../ollama/ollama run andrewcanis/command-r:q4_K_M 'hi'
	../ollama/ollama run andrewcanis/command-r:q4_K_S 'hi'
	../ollama/ollama run andrewcanis/command-r:q5_0 'hi'
	../ollama/ollama run andrewcanis/command-r:q5_K_M 'hi'
	../ollama/ollama run andrewcanis/command-r:q5_K_S 'hi'
	../ollama/ollama run andrewcanis/command-r:q6_K 'hi'
	../ollama/ollama run andrewcanis/command-r:q8_0 'hi'
```
The default command-r model uses q4_0 quantization:
```
	../ollama/ollama run andrewcanis/command-r 'hi'
```

Maintainers: is it possible to migrate this to an official space so user's don't need to include andrewcanis?

**Comment by jackielii** [comment]
@acanis Thanks so much for your efforts, I managed to run this model and it's giving good results. However, I have a suggestion:

The template should be:

```
<BOS_TOKEN>{{ if .System }}<|START_OF_TURN_TOKEN|><|SYSTEM_TOKEN|>{{ .System }}<|END_OF_TURN_TOKEN|>{{ end }}{{ if .Prompt }}<|START_OF_TURN_TOKEN|><|USER_TOKEN|>{{ .Prompt }}<|END_OF_TURN_TOKEN|>{{ end }}<|START_OF_TURN_TOKEN|><|CHATBOT_TOKEN|>{{ .Response }}
```

Basically this adds the `{{ if .Prompt }} ... {{ end }}` block so that we render the correct results per Cohere's example: https://huggingface.co/CohereForAI/c4ai-command-r-v01

E.g. I have the following message:

```go
			messages: []api.Message{
				{Role: "system", Content: "i'm system"},
				{Role: "user", Content: "i'm user"},
				{Role: "system", Content: "I'm system again"},
			},
```

Without the `if end` block, it renders:

```
<BOS_TOKEN><|START_OF_TURN_TOKEN|><|SYSTEM_TOKEN|>i'm system<|END_OF_TURN_TOKEN|><|START_OF_TURN_TOKEN|><|USER_TOKEN|>i'm user<|END_OF_TURN_TOKEN|><|START_OF_TURN_TOKEN|><|CHATBOT_TOKEN|><BOS_TOKEN><|START_OF_TURN_TOKEN|><|SYSTEM_TOKEN|>I'm system again<|END_OF_TURN_TOKEN|><|START_OF_TURN_TOKEN|><|USER_TOKEN|><|END_OF_TURN_TOKEN|><|START_OF_TURN_TOKEN|><|CHATBOT_TOKEN|>
```

With it it renders:

```
<BOS_TOKEN><|START_OF_TURN_TOKEN|><|SYSTEM_TOKEN|>i'm system<|END_OF_TURN_TOKEN|><|START_OF_TURN_TOKEN|><|USER_TOKEN|>i'm user<|END_OF_TURN_TOKEN|><|START_OF_TURN_TOKEN|><|CHATBOT_TOKEN|><BOS_TOKEN><|START_OF_TURN_TOKEN|><|SYSTEM_TOKEN|>I'm system again<|END_OF_TURN_TOKEN|><|START_OF_TURN_TOKEN|><|CHATBOT_TOKEN|>
```

Scroll to the right you'll see the correct one doesn't have the redundant `<|USER_TOKEN|>` section.


Thanks & Regards,

**Comment by josharian** [comment]
It'd be nice to get this in, since current `main` doesn't build, due to submodule skew.

**Comment by jackielii** [comment]
Ok, There are actually more problem with the template rendering. If we have more system message at the end, it just won't render correctly: https://github.com/ollama/ollama/issues/3287

**Comment by EdwHA** [comment]
windows 10
ollama run c4:latest
Error: exception error loading model architecture: unknown model architecture: 'command-r'

**Comment by acanis** [comment]
Looks like this has been added in: https://github.com/ollama/ollama/releases/tag/v0.1.30
So this PR can be closed

**Pull request closed without merging**
