### PR TITLE
Basic whitespace detection in JSON mode

### PR DESCRIPTION
**Pull request by jmorganca**
This stops hanging from infinite whitespace generation by detecting 100 consecutive whitespace tokens and cancelling

Other ideas:

- [ ] Repetition detection – detect the repetition of the same string over and over again
- [ ] Only do this after detecting a full json object
- [ ] Lower whitespace logit bias when using JSON mode (might affect outcome of the response)
- [ ] Force user to specify `JSON` in the prompt (might be hard for folks to know this, this is what OpenAI does)

### CODE REVIEW

**Comment by BruceMacD** [comment]
Seems like a reasonable approach. For point 3 (force user to specify `JSON` in the prompt) in one of the open issues related to this `JSON` actually is specified in the prompt, but the issue persists. So that won't be a complete fix, although it will help in many cases.

**Comment by jmorganca** [comment]
@BruceMacD thanks! The other approach might just be "repetition detection", which we've seen outside of json mode too for smaller models

**Comment by fergusq** [comment]
Why not just disallow space at the end in the grammar that is used to constrain the output? Right now it allows tailing whitespace, but I see no reason for that. It should only allow that inside objects, not after the whole JSON value.

**Comment by BruceMacD** [comment]
superseded by #3080

**Pull request closed without merging**
