### PR TITLE
Improve usability with Bash completion for Ollama on Linux

### PR DESCRIPTION
**Pull request by aosan**
Please review this PR for adding Bash completion to install.sh for Linux.

Currently works for all arguments and options, including autocomplete for long model names (yay!)

`ollama ls` works, but it's missing from the -h/--help and ollama listing. I'll open a separate issue for it.

It does not include  autocomplete for `ollama rm` as I consider easy destructive actions would need user confirmation before execution. I'll also create an issue for it.

This version of install.sh has been tested successfully on Fedora 39, Ubuntu 23.10 and Debian 12.5.

### CODE REVIEW

**Comment by hamirmahal** [comment]
I was just about to open an issue for this.

**Review by hamirmahal — COMMENTED** [review]
@jmorganca or @mxyng would either of you be able to review this?

**Comment by ericcurtin** [comment]
I'd take this contribution in:

https://github.com/ericcurtin/podman-ollama

just saying...

**Comment by ericcurtin** [comment]
I merged the change here with you as co-author https://github.com/ericcurtin/podman-ollama/pull/54

**Comment by jmorganca** [comment]
Hi @aosan thank you so much for the PR! Sorry for the late review. I'm a little hesitant to merge this vs building it into the `ollama` binary (e.g. https://github.com/ollama/ollama/pull/980) since that will make sure it stays up to date with new commands etc. That said I really appreciate the time and effect to add this to the install script

**Comment by lee-b** [comment]
It looks like this only completes models for `run`?  In other ways it's more complete than my script, but mine (just thrown together this morning, based on another script I found + some continue.dev work) completes model names for `cp` and `create` too.  This functionality should probably should be folded in.

```
_complete_ollama() {
   local cur prev words cword
   _init_completion -n : || return

   if [[ ${cword} -eq 1 ]]; then
       COMPREPLY=($(compgen -W "serve create show run push pull list ps cp rm help" -- "${cur}"))
   elif [[ ${words[1]} == "create" && ${prev} != "--file" && ${prev} != "-f" ]] && [ ${cword} -eq 2 ]; then
       WORDLIST=$((ollama list 2>/dev/null || echo "") | tail -n +2 | cut -d "	" -f 1)
       COMPREPLY=($(compgen -W "${WORDLIST}" -- "${cur}"))
   elif [[ ${words[1]} == "create" && (${prev} == "--file" || ${prev} == "-f") ]]; then
       COMPREPLY=($(compgen -f -- "$cur"))
   elif [[ ${words[1]} == "cp" ]] && [ ${cword} -gt 1 ]; then
       if [ ${cword} -eq 2 ]; then
           WORDLIST=$((ollama list 2>/dev/null || echo "") | tail -n +2 | cut -d "	" -f 1)
           COMPREPLY=($(compgen -W "${WORDLIST}" -- "${cur}"))
       elif [ ${cword} -eq 3 ]; then
           WORDLIST=$((ollama list 2>/dev/null || echo "") | tail -n +2 | cut -d "	" -f 1)
           COMPREPLY=($(compgen -W "${WORDLIST}" -- "${cur}") )
       fi
   fi
}

_complete_ollama_trash() {
   local cur words cword
   _init_completion -n : || return

   if [[ ${cword} -eq 1 ]]; then
       WORDLIST=$((ollama list 2>/dev/null || echo "") | tail -n +2 | cut -d "	" -f 1)
       COMPREPLY=($(compgen -W "${WORDLIST}" -- "${cur}"))
       __ltrim_colon_completions "$cur"
   elif [[ ${cword} -eq 2 ]] && [ "${prev}" != "" ]; then
       WORDLIST=$((ollama list 2>/dev/null || echo "") | tail -n +2 | cut -d "	" -f 1)
       COMPREPLY=($(compgen -W "${WORDLIST} ${cur}") )
   fi
}

complete -F _complete_ollama ollama
complete -F _complete_ollama_trash ollama-trash
```

**Pull request closed without merging**
