### PR TITLE
feat: http client bandwidth limit for pulling and pushing

### PR DESCRIPTION
**Pull request by erenaslandev**
I don't want to use all the bandwidth of my internet for downloading models, I want to use it for other things in the background. I tried to add bandwidth limiting for this.

#2006 was already open, so I guess it solves that too.

### CODE REVIEW

**Comment by erenaslandev** [comment]
At the moment, it is not possible to allocate the cap limit to others after one part is finished.

**Comment by erenaslandev** [comment]
example usage
```sh
ollama pull dolphincoder:15b-starcoder2-q5_K_M --bandwidth "600 KB"
```
image

**Comment by baptistejamin** [comment]
Very much needed! Thanks

**Comment by jmorganca** [comment]
Hi @erenaslandev thanks for the PR! A few months ago Ollama lowered the number of connections opened when downloading and uploading models – issues around this should be fixed now. However let me know if you're still seeing bandwidth saturation issues and we can revisit.

**Comment by erenaslandev** [comment]
this problem is not related to ollama, it was a feature that was useful when the user's bandwidth was low.

**Pull request closed without merging**
