### PR TITLE
Intel GPU build support

### LINKED ISSUE #1590: Add support for Intel Arc GPUs?

### PR DESCRIPTION
**Pull request by dhiltgen**
This enables linux, but still needs some more work to get it wired up to the Windows official builds.

Fixes #1590

### CODE REVIEW

**Comment by tannisroot** [comment]
What if just Linux support is merged and Windows support is added later?
If the delay is due to crashes in the Intel driver, it could take a while for Intel guys to diagnose and fix it.
This would allow Linux users to more easily test the SYCL backend and test things to iron out any potential kinks in advance :)

**Comment by Minionflo** [comment]
Any Updates on this?

**Comment by tallesl** [comment]
Any chance that we get this... ever?

**Comment by itlackey** [comment]
I threw together is article detailing how I am using docker to run Ollama on my A770: 
https://dev.to/itlackey/run-ollama-on-intel-arc-gpu-ipex-4e4k

This is the easiest approach I have found so far. It looks like it may be a minute before it's included in the official release/docker image. Hopefully this helps make use of these GPUs in the meantime. ;)

**Comment by tkarna** [comment]
You can use Intel GPUs via ipex (Intel Extension for PyTorch) as @itlackey mentioned. It, however, is a bit of an overkill if you only need ollama (ipex also installs PyTorch and many other packages).

As an alternative, you can build ollama from sources with SYCL support. Here's [an example](https://gist.github.com/tkarna/237d5acd825b139c85a9824ca677e0f5) for Ubuntu 22.04. Note, however, that at the moment only supports Intel's _discrete_ GPUs are supported, not _integrated_ GPUs. For integrated GPUs, ipex is the only approach that I know of.

**Comment by itlackey** [comment]
Thanks @tkarna  but myself and many others have struggled to compile the source and have it work properly. It is not a straightforward process.
The IPEX image may be a little bloated, but it works and is easy to get running.

Also, you could make your own Docker image based on the IPEX image and only copy what you need from it.

**Comment by WAH19** [comment]
> I threw together is article detailing how I am using docker to run Ollama on my A770: https://dev.to/itlackey/run-ollama-on-intel-arc-gpu-ipex-4e4k
> 
> This is the easiest approach I have found so far. It looks like it may be a minute before it's included in the official release/docker image. Hopefully this helps make use of these GPUs in the meantime. ;)

I am getting this error.  Any help? followed your website
time=2025-01-24T05:52:48.872+08:00 level=ERROR source=sched.go:455 msg="error loading llama server" error="llama runner process has terminated: error loading model: No device of requested type available. Please check https://software.intel.com/content/www/us/en/develop/articles/intel-oneapi-dpcpp-system-requirements.html -1 (PI_ERROR_DEVICE_NOT_FOUND)\nllama_load_model_from_file: failed to load model"

**Comment by NeoZhangJianyu** [comment]
miss to install GPU driver or driver is not available.
What's: GPU, OS?

**Comment by WAH19** [comment]
> miss to install GPU driver or driver is not available. What's: GPU, OS?
Ubuntu 24.04.1 LTS
 clinfo | grep "Device Name"
  Device Name                                     Intel(R) Graphics [0x56a1]
    Device Name                                   Intel(R) Graphics [0x56a1]
    Device Name                                   Intel(R) Graphics [0x56a1]
    Device Name                                   Intel(R) Graphics [0x56a1]

**Comment by NeoZhangJianyu** [comment]
For docker support GPU, please refer the cmd in https://www.intel.com/content/www/us/en/docs/distribution-for-gdb/tutorial-debugging-dpcpp-linux/2023-2/docker-installation.html

sycl-ls is a tool included in oneAPI base toolkit. You need to install the package and enable it before execute it.

**Pull request closed without merging**
