### PR TITLE
feat: support registry basic auth

### PR DESCRIPTION
**Pull request by qcu266**
support pull/push model from/to private oci registry.

relates: https://github.com/ollama/ollama/issues/2745

### CODE REVIEW

**Comment by NPhMKgbDNy1M** [comment]
This would be very nice for my company, since we are using a nexus mirror and proxy.

**Comment by chlins** [comment]
If this pull request could be merged, it would greatly benefit enterprise users, as they typically cannot use unauthenticated registries. Implementing basic authentication would enable users to manage their models on a private registry more effectively.

**Comment by alex-vg** [comment]
I apologize for the direct mention, @jmorganca, but when you have a moment, would you kindly consider reviewing this? Thank you!

**Comment by jmorganca** [comment]
Hi @qcu266 thanks so much for the PR. While this is something we'd like to support in the future, Ollama currently supports an authentication scheme based on keypairs. Adding too many alternative authentication schemes might make it harder to evolve Ollama's registry code in the future (e.g. to make it faster), and so for the time being it would be best we stick to one scheme.

**Comment by ericcurtin** [comment]
We will be enabling the functionality to push and pull models to OCI registries in RamaLama pending completion of the new "podman artifact" command:

https://github.com/containers/ramalama

**Comment by ericcurtin** [comment]
@qcu266 @NPhMKgbDNy1M @chlins @alex-vg we have this in docker model runner now and we've put effort into cleaning up the github repo to make it more contributor friendly, please star, fork and contribute:

https://github.com/docker/model-runner

**Pull request closed without merging**
