### PR TITLE
docs: add OpenGPA in Readme Web & Desktop

### PR DESCRIPTION
**Pull request by eschnou**
Hello,

OpenGPA is a offline-first open-source Enterprise Agentic Application. It has Ollama support and Ollama specific documentation (https://github.com/eschnou/OpenGPA/blob/main/documentation/offline.md). This integration allows for a fully offline experience, which is required in some critical enterprise environments.

Thanks for the awesome work on Ollama and thanks for reviewing and merging this one 🤩

Best regards,

Laurent

### CODE REVIEW

**Review by jmorganca — APPROVED** [review]
Thanks!

**Comment by jmorganca** [comment]
@eschnou this needs a rebase

**Comment by eschnou** [comment]
@jmorganca Thanks for the review. PR updated.

**Comment by eschnou** [comment]
Hi @jmorganca - any chance you could merge this one which is approved and rebased. 🙏 Thanks!

**Review by mchiang0610 — APPROVED** [review]

**Pull request merged**
